/*
 * MercadoLibre API
 * MercadoLibre API Documentation.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-08-06T14:21:46.668-03:00")
public class Configuration {
    private static ApiClient defaultApiClient = new ApiClient();

    /**
     * Get the default API client, which would be used when creating API
     * instances without providing an API client.
     *
     * @return Default API client
     */
    public static ApiClient getDefaultApiClient() {
        return defaultApiClient;
    }

    /**
     * Set the default API client, which would be used when creating API
     * instances without providing an API client.
     *
     * @param apiClient API client
     */
    public static void setDefaultApiClient(ApiClient apiClient) {
        defaultApiClient = apiClient;
    }


    public static enum AuthUrls {
        MLA("https://auth.mercadolibre.com.ar"), // Argentina
        MLB("https://auth.mercadolivre.com.br"), // Brasil
        MCO("https://auth.mercadolibre.com.co"), // Colombia
        MCR("https://auth.mercadolibre.com.cr"), // Costa Rica
        MEC("https://auth.mercadolibre.com.ec"), // Ecuador
        MLC("https://auth.mercadolibre.cl"), // Chile
        MLM("https://auth.mercadolibre.com.mx"), // Mexico
        MLU("https://auth.mercadolibre.com.uy"), // Uruguay
        MLV("https://auth.mercadolibre.com.ve"), // Venezuela
        MPA("https://auth.mercadolibre.com.pa"), // Panama
        MPE("https://auth.mercadolibre.com.pe"), // Peru
        MPT("https://auth.mercadolibre.com.pt"), // Portugal
        MRD("https://auth.mercadolibre.com.do"), // Dominicana
        CBT("https://global-selling.mercadolibre.com"); // CBT

        private String value;

        private AuthUrls(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }
    }

}
