/*
 * MELI Markeplace SDK
 * This is a the codebase to generate a SDK for Open Platform Marketplace
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package meli.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import meli.model.AttributesValueStruct;
import meli.model.AttributesValues;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Attributes
 */
public class AttributesTest {
    private final Attributes model = new Attributes();

    /**
     * Model tests for Attributes
     */
    @Test
    public void testAttributes() {
        // TODO: test Attributes
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'valueId'
     */
    @Test
    public void valueIdTest() {
        // TODO: test valueId
    }

    /**
     * Test the property 'valueName'
     */
    @Test
    public void valueNameTest() {
        // TODO: test valueName
    }

    /**
     * Test the property 'valueStruct'
     */
    @Test
    public void valueStructTest() {
        // TODO: test valueStruct
    }

    /**
     * Test the property 'values'
     */
    @Test
    public void valuesTest() {
        // TODO: test values
    }

    /**
     * Test the property 'attributeGroupId'
     */
    @Test
    public void attributeGroupIdTest() {
        // TODO: test attributeGroupId
    }

    /**
     * Test the property 'attributeGroupName'
     */
    @Test
    public void attributeGroupNameTest() {
        // TODO: test attributeGroupName
    }

}
