/*
 * MELI Markeplace SDK
 * This is a the codebase to generate a SDK for Open Platform Marketplace
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package meli.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import meli.model.Attributes;
import meli.model.ItemPictures;
import meli.model.Variations;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Item
 */
public class ItemTest {
    private final Item model = new Item();

    /**
     * Model tests for Item
     */
    @Test
    public void testItem() {
        // TODO: test Item
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'categoryId'
     */
    @Test
    public void categoryIdTest() {
        // TODO: test categoryId
    }

    /**
     * Test the property 'price'
     */
    @Test
    public void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'currencyId'
     */
    @Test
    public void currencyIdTest() {
        // TODO: test currencyId
    }

    /**
     * Test the property 'availableQuantity'
     */
    @Test
    public void availableQuantityTest() {
        // TODO: test availableQuantity
    }

    /**
     * Test the property 'buyingMode'
     */
    @Test
    public void buyingModeTest() {
        // TODO: test buyingMode
    }

    /**
     * Test the property 'listingTypeId'
     */
    @Test
    public void listingTypeIdTest() {
        // TODO: test listingTypeId
    }

    /**
     * Test the property 'condition'
     */
    @Test
    public void conditionTest() {
        // TODO: test condition
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'videoId'
     */
    @Test
    public void videoIdTest() {
        // TODO: test videoId
    }

    /**
     * Test the property 'pictures'
     */
    @Test
    public void picturesTest() {
        // TODO: test pictures
    }

    /**
     * Test the property 'attributes'
     */
    @Test
    public void attributesTest() {
        // TODO: test attributes
    }

    /**
     * Test the property 'variations'
     */
    @Test
    public void variationsTest() {
        // TODO: test variations
    }

}
