/*
 * MELI Markeplace SDK
 * This is a the codebase to generate a SDK for Open Platform Marketplace
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package meli.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for VariationsAttributeCombinations
 */
public class VariationsAttributeCombinationsTest {
    private final VariationsAttributeCombinations model = new VariationsAttributeCombinations();

    /**
     * Model tests for VariationsAttributeCombinations
     */
    @Test
    public void testVariationsAttributeCombinations() {
        // TODO: test VariationsAttributeCombinations
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'valueId'
     */
    @Test
    public void valueIdTest() {
        // TODO: test valueId
    }

    /**
     * Test the property 'valueName'
     */
    @Test
    public void valueNameTest() {
        // TODO: test valueName
    }

}
