/*
 * MELI Markeplace SDK
 * This is a the codebase to generate a SDK for Open Platform Marketplace
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package meli.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import meli.model.VariationsAttributeCombinations;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Variations
 */
public class VariationsTest {
    private final Variations model = new Variations();

    /**
     * Model tests for Variations
     */
    @Test
    public void testVariations() {
        // TODO: test Variations
    }

    /**
     * Test the property 'price'
     */
    @Test
    public void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'attributeCombinations'
     */
    @Test
    public void attributeCombinationsTest() {
        // TODO: test attributeCombinations
    }

    /**
     * Test the property 'availableQuantity'
     */
    @Test
    public void availableQuantityTest() {
        // TODO: test availableQuantity
    }

    /**
     * Test the property 'soldQuantity'
     */
    @Test
    public void soldQuantityTest() {
        // TODO: test soldQuantity
    }

    /**
     * Test the property 'pictureIds'
     */
    @Test
    public void pictureIdsTest() {
        // TODO: test pictureIds
    }

}
