/*
 * MELI Markeplace SDK
 * This is a the codebase to generate a SDK for Open Platform Marketplace
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package meli.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * VariationsAttributeCombinations
 */

public class VariationsAttributeCombinations {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_VALUE_ID = "value_id";
  @SerializedName(SERIALIZED_NAME_VALUE_ID)
  private String valueId;

  public static final String SERIALIZED_NAME_VALUE_NAME = "value_name";
  @SerializedName(SERIALIZED_NAME_VALUE_NAME)
  private String valueName;


  public VariationsAttributeCombinations name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Color", value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public VariationsAttributeCombinations valueId(String valueId) {
    
    this.valueId = valueId;
    return this;
  }

   /**
   * Get valueId
   * @return valueId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "283165", value = "")

  public String getValueId() {
    return valueId;
  }


  public void setValueId(String valueId) {
    this.valueId = valueId;
  }


  public VariationsAttributeCombinations valueName(String valueName) {
    
    this.valueName = valueName;
    return this;
  }

   /**
   * Get valueName
   * @return valueName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Gris", value = "")

  public String getValueName() {
    return valueName;
  }


  public void setValueName(String valueName) {
    this.valueName = valueName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VariationsAttributeCombinations variationsAttributeCombinations = (VariationsAttributeCombinations) o;
    return Objects.equals(this.name, variationsAttributeCombinations.name) &&
        Objects.equals(this.valueId, variationsAttributeCombinations.valueId) &&
        Objects.equals(this.valueName, variationsAttributeCombinations.valueName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, valueId, valueName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VariationsAttributeCombinations {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    valueId: ").append(toIndentedString(valueId)).append("\n");
    sb.append("    valueName: ").append(toIndentedString(valueName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

