/*
 * MercadoLibre API
 * MercadoLibre API Documentation.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ImmediatePayment;
import java.util.ArrayList;
import java.util.List;

/**
 * Buy
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-08-06T14:21:46.668-03:00")
public class Buy {
  @JsonProperty("allow")
  private Boolean allow = null;

  @JsonProperty("codes")
  private List<String> codes = null;

  @JsonProperty("immediate_payment")
  private ImmediatePayment immediatePayment = null;

  public Buy allow(Boolean allow) {
    this.allow = allow;
    return this;
  }

   /**
   * Get allow
   * @return allow
  **/
  @ApiModelProperty(value = "")
  public Boolean isAllow() {
    return allow;
  }

  public void setAllow(Boolean allow) {
    this.allow = allow;
  }

  public Buy codes(List<String> codes) {
    this.codes = codes;
    return this;
  }

  public Buy addCodesItem(String codesItem) {
    if (this.codes == null) {
      this.codes = new ArrayList<String>();
    }
    this.codes.add(codesItem);
    return this;
  }

   /**
   * Get codes
   * @return codes
  **/
  @ApiModelProperty(value = "")
  public List<String> getCodes() {
    return codes;
  }

  public void setCodes(List<String> codes) {
    this.codes = codes;
  }

  public Buy immediatePayment(ImmediatePayment immediatePayment) {
    this.immediatePayment = immediatePayment;
    return this;
  }

   /**
   * Get immediatePayment
   * @return immediatePayment
  **/
  @ApiModelProperty(value = "")
  public ImmediatePayment getImmediatePayment() {
    return immediatePayment;
  }

  public void setImmediatePayment(ImmediatePayment immediatePayment) {
    this.immediatePayment = immediatePayment;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Buy buy = (Buy) o;
    return Objects.equals(this.allow, buy.allow) &&
        Objects.equals(this.codes, buy.codes) &&
        Objects.equals(this.immediatePayment, buy.immediatePayment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allow, codes, immediatePayment);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Buy {\n");
    
    sb.append("    allow: ").append(toIndentedString(allow)).append("\n");
    sb.append("    codes: ").append(toIndentedString(codes)).append("\n");
    sb.append("    immediatePayment: ").append(toIndentedString(immediatePayment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

