/*
 * MercadoLibre API
 * MercadoLibre API Documentation.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Canceled;
import io.swagger.client.model.NotYetRated;
import io.swagger.client.model.Unrated;

/**
 * BuyerReputationTransactions
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-08-06T14:21:46.668-03:00")
public class BuyerReputationTransactions {
  @JsonProperty("canceled")
  private Canceled canceled = null;

  @JsonProperty("completed")
  private Object completed = null;

  @JsonProperty("not_yet_rated")
  private NotYetRated notYetRated = null;

  @JsonProperty("period")
  private String period = null;

  @JsonProperty("total")
  private Object total = null;

  @JsonProperty("unrated")
  private Unrated unrated = null;

  public BuyerReputationTransactions canceled(Canceled canceled) {
    this.canceled = canceled;
    return this;
  }

   /**
   * Get canceled
   * @return canceled
  **/
  @ApiModelProperty(value = "")
  public Canceled getCanceled() {
    return canceled;
  }

  public void setCanceled(Canceled canceled) {
    this.canceled = canceled;
  }

  public BuyerReputationTransactions completed(Object completed) {
    this.completed = completed;
    return this;
  }

   /**
   * Get completed
   * @return completed
  **/
  @ApiModelProperty(value = "")
  public Object getCompleted() {
    return completed;
  }

  public void setCompleted(Object completed) {
    this.completed = completed;
  }

  public BuyerReputationTransactions notYetRated(NotYetRated notYetRated) {
    this.notYetRated = notYetRated;
    return this;
  }

   /**
   * Get notYetRated
   * @return notYetRated
  **/
  @ApiModelProperty(value = "")
  public NotYetRated getNotYetRated() {
    return notYetRated;
  }

  public void setNotYetRated(NotYetRated notYetRated) {
    this.notYetRated = notYetRated;
  }

  public BuyerReputationTransactions period(String period) {
    this.period = period;
    return this;
  }

   /**
   * Get period
   * @return period
  **/
  @ApiModelProperty(value = "")
  public String getPeriod() {
    return period;
  }

  public void setPeriod(String period) {
    this.period = period;
  }

  public BuyerReputationTransactions total(Object total) {
    this.total = total;
    return this;
  }

   /**
   * Get total
   * @return total
  **/
  @ApiModelProperty(value = "")
  public Object getTotal() {
    return total;
  }

  public void setTotal(Object total) {
    this.total = total;
  }

  public BuyerReputationTransactions unrated(Unrated unrated) {
    this.unrated = unrated;
    return this;
  }

   /**
   * Get unrated
   * @return unrated
  **/
  @ApiModelProperty(value = "")
  public Unrated getUnrated() {
    return unrated;
  }

  public void setUnrated(Unrated unrated) {
    this.unrated = unrated;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BuyerReputationTransactions buyerReputationTransactions = (BuyerReputationTransactions) o;
    return Objects.equals(this.canceled, buyerReputationTransactions.canceled) &&
        Objects.equals(this.completed, buyerReputationTransactions.completed) &&
        Objects.equals(this.notYetRated, buyerReputationTransactions.notYetRated) &&
        Objects.equals(this.period, buyerReputationTransactions.period) &&
        Objects.equals(this.total, buyerReputationTransactions.total) &&
        Objects.equals(this.unrated, buyerReputationTransactions.unrated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(canceled, completed, notYetRated, period, total, unrated);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BuyerReputationTransactions {\n");
    
    sb.append("    canceled: ").append(toIndentedString(canceled)).append("\n");
    sb.append("    completed: ").append(toIndentedString(completed)).append("\n");
    sb.append("    notYetRated: ").append(toIndentedString(notYetRated)).append("\n");
    sb.append("    period: ").append(toIndentedString(period)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    unrated: ").append(toIndentedString(unrated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

