/*
 * MercadoLibre API
 * MercadoLibre API Documentation.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.PredictionPathFromRoot;
import java.util.ArrayList;
import java.util.List;

/**
 * CategoryPrediction
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-08-06T14:21:46.668-03:00")
public class CategoryPrediction {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("path_from_root")
  private List<PredictionPathFromRoot> pathFromRoot = null;

  @JsonProperty("prediction_probability")
  private Double predictionProbability = null;

  @JsonProperty("shipping_modes")
  private List<String> shippingModes = null;

  public CategoryPrediction id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public CategoryPrediction name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CategoryPrediction pathFromRoot(List<PredictionPathFromRoot> pathFromRoot) {
    this.pathFromRoot = pathFromRoot;
    return this;
  }

  public CategoryPrediction addPathFromRootItem(PredictionPathFromRoot pathFromRootItem) {
    if (this.pathFromRoot == null) {
      this.pathFromRoot = new ArrayList<PredictionPathFromRoot>();
    }
    this.pathFromRoot.add(pathFromRootItem);
    return this;
  }

   /**
   * Get pathFromRoot
   * @return pathFromRoot
  **/
  @ApiModelProperty(value = "")
  public List<PredictionPathFromRoot> getPathFromRoot() {
    return pathFromRoot;
  }

  public void setPathFromRoot(List<PredictionPathFromRoot> pathFromRoot) {
    this.pathFromRoot = pathFromRoot;
  }

  public CategoryPrediction predictionProbability(Double predictionProbability) {
    this.predictionProbability = predictionProbability;
    return this;
  }

   /**
   * Get predictionProbability
   * @return predictionProbability
  **/
  @ApiModelProperty(value = "")
  public Double getPredictionProbability() {
    return predictionProbability;
  }

  public void setPredictionProbability(Double predictionProbability) {
    this.predictionProbability = predictionProbability;
  }

  public CategoryPrediction shippingModes(List<String> shippingModes) {
    this.shippingModes = shippingModes;
    return this;
  }

  public CategoryPrediction addShippingModesItem(String shippingModesItem) {
    if (this.shippingModes == null) {
      this.shippingModes = new ArrayList<String>();
    }
    this.shippingModes.add(shippingModesItem);
    return this;
  }

   /**
   * Get shippingModes
   * @return shippingModes
  **/
  @ApiModelProperty(value = "")
  public List<String> getShippingModes() {
    return shippingModes;
  }

  public void setShippingModes(List<String> shippingModes) {
    this.shippingModes = shippingModes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CategoryPrediction categoryPrediction = (CategoryPrediction) o;
    return Objects.equals(this.id, categoryPrediction.id) &&
        Objects.equals(this.name, categoryPrediction.name) &&
        Objects.equals(this.pathFromRoot, categoryPrediction.pathFromRoot) &&
        Objects.equals(this.predictionProbability, categoryPrediction.predictionProbability) &&
        Objects.equals(this.shippingModes, categoryPrediction.shippingModes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, pathFromRoot, predictionProbability, shippingModes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CategoryPrediction {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    pathFromRoot: ").append(toIndentedString(pathFromRoot)).append("\n");
    sb.append("    predictionProbability: ").append(toIndentedString(predictionProbability)).append("\n");
    sb.append("    shippingModes: ").append(toIndentedString(shippingModes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

