/*
 * MercadoLibre API
 * MercadoLibre API Documentation.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Offset;
import io.swagger.client.model.TimeFrame;

/**
 * EstimatedDeliveryTime
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-08-06T14:21:46.668-03:00")
public class EstimatedDeliveryTime {
  @JsonProperty("type")
  private String type = null;

  @JsonProperty("date")
  private String date = null;

  @JsonProperty("unit")
  private String unit = null;

  @JsonProperty("offset")
  private Offset offset = null;

  @JsonProperty("time_frame")
  private TimeFrame timeFrame = null;

  @JsonProperty("pay_before")
  private Object payBefore = null;

  @JsonProperty("shipping")
  private Integer shipping = null;

  @JsonProperty("handling")
  private Object handling = null;

  @JsonProperty("schedule")
  private Object schedule = null;

  public EstimatedDeliveryTime type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public EstimatedDeliveryTime date(String date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @ApiModelProperty(value = "")
  public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }

  public EstimatedDeliveryTime unit(String unit) {
    this.unit = unit;
    return this;
  }

   /**
   * Get unit
   * @return unit
  **/
  @ApiModelProperty(value = "")
  public String getUnit() {
    return unit;
  }

  public void setUnit(String unit) {
    this.unit = unit;
  }

  public EstimatedDeliveryTime offset(Offset offset) {
    this.offset = offset;
    return this;
  }

   /**
   * Get offset
   * @return offset
  **/
  @ApiModelProperty(value = "")
  public Offset getOffset() {
    return offset;
  }

  public void setOffset(Offset offset) {
    this.offset = offset;
  }

  public EstimatedDeliveryTime timeFrame(TimeFrame timeFrame) {
    this.timeFrame = timeFrame;
    return this;
  }

   /**
   * Get timeFrame
   * @return timeFrame
  **/
  @ApiModelProperty(value = "")
  public TimeFrame getTimeFrame() {
    return timeFrame;
  }

  public void setTimeFrame(TimeFrame timeFrame) {
    this.timeFrame = timeFrame;
  }

  public EstimatedDeliveryTime payBefore(Object payBefore) {
    this.payBefore = payBefore;
    return this;
  }

   /**
   * Get payBefore
   * @return payBefore
  **/
  @ApiModelProperty(value = "")
  public Object getPayBefore() {
    return payBefore;
  }

  public void setPayBefore(Object payBefore) {
    this.payBefore = payBefore;
  }

  public EstimatedDeliveryTime shipping(Integer shipping) {
    this.shipping = shipping;
    return this;
  }

   /**
   * Get shipping
   * @return shipping
  **/
  @ApiModelProperty(value = "")
  public Integer getShipping() {
    return shipping;
  }

  public void setShipping(Integer shipping) {
    this.shipping = shipping;
  }

  public EstimatedDeliveryTime handling(Object handling) {
    this.handling = handling;
    return this;
  }

   /**
   * Get handling
   * @return handling
  **/
  @ApiModelProperty(value = "")
  public Object getHandling() {
    return handling;
  }

  public void setHandling(Object handling) {
    this.handling = handling;
  }

  public EstimatedDeliveryTime schedule(Object schedule) {
    this.schedule = schedule;
    return this;
  }

   /**
   * Get schedule
   * @return schedule
  **/
  @ApiModelProperty(value = "")
  public Object getSchedule() {
    return schedule;
  }

  public void setSchedule(Object schedule) {
    this.schedule = schedule;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EstimatedDeliveryTime estimatedDeliveryTime = (EstimatedDeliveryTime) o;
    return Objects.equals(this.type, estimatedDeliveryTime.type) &&
        Objects.equals(this.date, estimatedDeliveryTime.date) &&
        Objects.equals(this.unit, estimatedDeliveryTime.unit) &&
        Objects.equals(this.offset, estimatedDeliveryTime.offset) &&
        Objects.equals(this.timeFrame, estimatedDeliveryTime.timeFrame) &&
        Objects.equals(this.payBefore, estimatedDeliveryTime.payBefore) &&
        Objects.equals(this.shipping, estimatedDeliveryTime.shipping) &&
        Objects.equals(this.handling, estimatedDeliveryTime.handling) &&
        Objects.equals(this.schedule, estimatedDeliveryTime.schedule);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, date, unit, offset, timeFrame, payBefore, shipping, handling, schedule);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EstimatedDeliveryTime {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
    sb.append("    offset: ").append(toIndentedString(offset)).append("\n");
    sb.append("    timeFrame: ").append(toIndentedString(timeFrame)).append("\n");
    sb.append("    payBefore: ").append(toIndentedString(payBefore)).append("\n");
    sb.append("    shipping: ").append(toIndentedString(shipping)).append("\n");
    sb.append("    handling: ").append(toIndentedString(handling)).append("\n");
    sb.append("    schedule: ").append(toIndentedString(schedule)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

