/*
 * MercadoLibre API
 * MercadoLibre API Documentation.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Rules;
import java.util.ArrayList;
import java.util.List;

/**
 * IdentificationTypesRules
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-08-06T14:21:46.668-03:00")
public class IdentificationTypesRules {
  @JsonProperty("identification_type")
  private String identificationType = null;

  @JsonProperty("rules")
  private List<Rules> rules = null;

  public IdentificationTypesRules identificationType(String identificationType) {
    this.identificationType = identificationType;
    return this;
  }

   /**
   * Get identificationType
   * @return identificationType
  **/
  @ApiModelProperty(value = "")
  public String getIdentificationType() {
    return identificationType;
  }

  public void setIdentificationType(String identificationType) {
    this.identificationType = identificationType;
  }

  public IdentificationTypesRules rules(List<Rules> rules) {
    this.rules = rules;
    return this;
  }

  public IdentificationTypesRules addRulesItem(Rules rulesItem) {
    if (this.rules == null) {
      this.rules = new ArrayList<Rules>();
    }
    this.rules.add(rulesItem);
    return this;
  }

   /**
   * Get rules
   * @return rules
  **/
  @ApiModelProperty(value = "")
  public List<Rules> getRules() {
    return rules;
  }

  public void setRules(List<Rules> rules) {
    this.rules = rules;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IdentificationTypesRules identificationTypesRules = (IdentificationTypesRules) o;
    return Objects.equals(this.identificationType, identificationTypesRules.identificationType) &&
        Objects.equals(this.rules, identificationTypesRules.rules);
  }

  @Override
  public int hashCode() {
    return Objects.hash(identificationType, rules);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IdentificationTypesRules {\n");
    
    sb.append("    identificationType: ").append(toIndentedString(identificationType)).append("\n");
    sb.append("    rules: ").append(toIndentedString(rules)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

