/*
 * MercadoLibre API
 * MercadoLibre API Documentation.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ItemJson
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-14T10:44:34.055-03:00")
public class ItemJson {
  @JsonProperty("listing_type_id")
  private String listingTypeId = null;

  @JsonProperty("pictures")
  private List<Pictures> pictures = null;

  @JsonProperty("title")
  private String title = null;

  @JsonProperty("available_quantity")
  private Integer availableQuantity = null;

  @JsonProperty("category_id")
  private String categoryId = null;

  @JsonProperty("buying_mode")
  private String buyingMode = null;

  @JsonProperty("currency_id")
  private String currencyId = null;

  @JsonProperty("condition")
  private String condition = null;

  @JsonProperty("site_id")
  private String siteId = null;

  @JsonProperty("price")
  private Integer price = null;

  @JsonProperty("official_store_id")
  private Integer officialStoreId = null;

  @JsonProperty("variations")
  private List<Variations> variations = null;

  @JsonProperty("attributes")
  private List<Attributes> attributes = null;

  @JsonProperty("shipping")
  private List<Shipping> shipping = null;

  public ItemJson listingTypeId(String listingTypeId) {
    this.listingTypeId = listingTypeId;
    return this;
  }

  /**
   * Get listingTypeId
   * @return listingTypeId
   **/
  @ApiModelProperty(value = "")
  public String getListingTypeId() {
    return listingTypeId;
  }

  public void setListingTypeId(String listingTypeId) {
    this.listingTypeId = listingTypeId;
  }

  public ItemJson pictures(List<Pictures> pictures) {
    this.pictures = pictures;
    return this;
  }

  public ItemJson addPicturesItem(Pictures picturesItem) {
    if (this.pictures == null) {
      this.pictures = new ArrayList<Pictures>();
    }
    this.pictures.add(picturesItem);
    return this;
  }

  /**
   * Get pictures
   * @return pictures
   **/
  @ApiModelProperty(value = "")
  public List<Pictures> getPictures() {
    return pictures;
  }

  public void setPictures(List<Pictures> pictures) {
    this.pictures = pictures;
  }

  public ItemJson title(String title) {
    this.title = title;
    return this;
  }

  /**
   * Get title
   * @return title
   **/
  @ApiModelProperty(value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public ItemJson availableQuantity(Integer availableQuantity) {
    this.availableQuantity = availableQuantity;
    return this;
  }

  /**
   * Get availableQuantity
   * @return availableQuantity
   **/
  @ApiModelProperty(value = "")
  public Integer getAvailableQuantity() {
    return availableQuantity;
  }

  public void setAvailableQuantity(Integer availableQuantity) {
    this.availableQuantity = availableQuantity;
  }

  public ItemJson categoryId(String categoryId) {
    this.categoryId = categoryId;
    return this;
  }

  /**
   * Get categoryId
   * @return categoryId
   **/
  @ApiModelProperty(value = "")
  public String getCategoryId() {
    return categoryId;
  }

  public void setCategoryId(String categoryId) {
    this.categoryId = categoryId;
  }

  public ItemJson buyingMode(String buyingMode) {
    this.buyingMode = buyingMode;
    return this;
  }

  /**
   * Get buyingMode
   * @return buyingMode
   **/
  @ApiModelProperty(value = "")
  public String getBuyingMode() {
    return buyingMode;
  }

  public void setBuyingMode(String buyingMode) {
    this.buyingMode = buyingMode;
  }

  public ItemJson currencyId(String currencyId) {
    this.currencyId = currencyId;
    return this;
  }

  /**
   * Get currencyId
   * @return currencyId
   **/
  @ApiModelProperty(value = "")
  public String getCurrencyId() {
    return currencyId;
  }

  public void setCurrencyId(String currencyId) {
    this.currencyId = currencyId;
  }

  public ItemJson condition(String condition) {
    this.condition = condition;
    return this;
  }

  /**
   * Get condition
   * @return condition
   **/
  @ApiModelProperty(value = "")
  public String getCondition() {
    return condition;
  }

  public void setCondition(String condition) {
    this.condition = condition;
  }

  public ItemJson siteId(String siteId) {
    this.siteId = siteId;
    return this;
  }

  /**
   * Get siteId
   * @return siteId
   **/
  @ApiModelProperty(value = "")
  public String getSiteId() {
    return siteId;
  }

  public void setSiteId(String siteId) {
    this.siteId = siteId;
  }

  public ItemJson price(Integer price) {
    this.price = price;
    return this;
  }

  /**
   * Get price
   * @return price
   **/
  @ApiModelProperty(value = "")
  public Integer getPrice() {
    return price;
  }

  public void setPrice(Integer price) {
    this.price = price;
  }

  public ItemJson officialStoreId(Integer officialStoreId) {
    this.officialStoreId = officialStoreId;
    return this;
  }

  /**
   * Get officialStoreId
   * @return officialStoreId
   **/
  @ApiModelProperty(value = "")
  public Integer getOfficialStoreId() {
    return officialStoreId;
  }

  public void setOfficialStoreId(Integer officialStoreId) {
    this.officialStoreId = officialStoreId;
  }

  public ItemJson variations(List<Variations> variations) {
    this.variations = variations;
    return this;
  }

  public ItemJson addVariationsItem(Variations variationsItem) {
    if (this.variations == null) {
      this.variations = new ArrayList<Variations>();
    }
    this.variations.add(variationsItem);
    return this;
  }

  /**
   * Get variations
   * @return variations
   **/
  @ApiModelProperty(value = "")
  public List<Variations> getVariations() {
    return variations;
  }

  public void setVariations(List<Variations> variations) {
    this.variations = variations;
  }

  public ItemJson attributes(List<Attributes> attributes) {
    this.attributes = attributes;
    return this;
  }

  public ItemJson addAttributesItem(Attributes attributesItem) {
    if (this.attributes == null) {
      this.attributes = new ArrayList<Attributes>();
    }
    this.attributes.add(attributesItem);
    return this;
  }

  /**
   * Get attributes
   * @return attributes
   **/
  @ApiModelProperty(value = "")
  public List<Attributes> getAttributes() {
    return attributes;
  }

  public void setAttributes(List<Attributes> attributes) {
    this.attributes = attributes;
  }

  public ItemJson shipping(List<Shipping> shipping) {
    this.shipping = shipping;
    return this;
  }

  public ItemJson addShippingItem(Shipping shippingItem) {
    if (this.shipping == null) {
      this.shipping = new ArrayList<Shipping>();
    }
    this.shipping.add(shippingItem);
    return this;
  }

  /**
   * Get shipping
   * @return shipping
   **/
  @ApiModelProperty(value = "")
  public List<Shipping> getShipping() {
    return shipping;
  }

  public void setShipping(List<Shipping> shipping) {
    this.shipping = shipping;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ItemJson itemJson = (ItemJson) o;
    return Objects.equals(this.listingTypeId, itemJson.listingTypeId) &&
            Objects.equals(this.pictures, itemJson.pictures) &&
            Objects.equals(this.title, itemJson.title) &&
            Objects.equals(this.availableQuantity, itemJson.availableQuantity) &&
            Objects.equals(this.categoryId, itemJson.categoryId) &&
            Objects.equals(this.buyingMode, itemJson.buyingMode) &&
            Objects.equals(this.currencyId, itemJson.currencyId) &&
            Objects.equals(this.condition, itemJson.condition) &&
            Objects.equals(this.siteId, itemJson.siteId) &&
            Objects.equals(this.price, itemJson.price) &&
            Objects.equals(this.officialStoreId, itemJson.officialStoreId) &&
            Objects.equals(this.variations, itemJson.variations) &&
            Objects.equals(this.attributes, itemJson.attributes) &&
            Objects.equals(this.shipping, itemJson.shipping);
  }

  @Override
  public int hashCode() {
    return Objects.hash(listingTypeId, pictures, title, availableQuantity, categoryId, buyingMode, currencyId, condition, siteId, price, officialStoreId, variations, attributes, shipping);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ItemJson {\n");

    sb.append("    listingTypeId: ").append(toIndentedString(listingTypeId)).append("\n");
    sb.append("    pictures: ").append(toIndentedString(pictures)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    availableQuantity: ").append(toIndentedString(availableQuantity)).append("\n");
    sb.append("    categoryId: ").append(toIndentedString(categoryId)).append("\n");
    sb.append("    buyingMode: ").append(toIndentedString(buyingMode)).append("\n");
    sb.append("    currencyId: ").append(toIndentedString(currencyId)).append("\n");
    sb.append("    condition: ").append(toIndentedString(condition)).append("\n");
    sb.append("    siteId: ").append(toIndentedString(siteId)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    officialStoreId: ").append(toIndentedString(officialStoreId)).append("\n");
    sb.append("    variations: ").append(toIndentedString(variations)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    shipping: ").append(toIndentedString(shipping)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

