/*
 * MercadoLibre API
 * MercadoLibre API Documentation.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.MessageAttachmentsValidations;
import io.swagger.client.model.MessageFrom;
import io.swagger.client.model.MessageModeration;
import io.swagger.client.model.MessageText;
import io.swagger.client.model.MessageTo;
import java.util.ArrayList;
import java.util.List;

/**
 * Message
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-08-06T14:21:46.668-03:00")
public class Message {
  @JsonProperty("message_id")
  private String messageId = null;

  @JsonProperty("date_received")
  private String dateReceived = null;

  @JsonProperty("date")
  private String date = null;

  @JsonProperty("date_available")
  private String dateAvailable = null;

  @JsonProperty("date_notified")
  private String dateNotified = null;

  @JsonProperty("date_read")
  private String dateRead = null;

  @JsonProperty("from")
  private MessageFrom from = null;

  @JsonProperty("to")
  private List<MessageTo> to = null;

  @JsonProperty("subject")
  private String subject = null;

  @JsonProperty("text")
  private MessageText text = null;

  @JsonProperty("attachments")
  private List<String> attachments = null;

  @JsonProperty("attachments_validations")
  private List<MessageAttachmentsValidations> attachmentsValidations = null;

  @JsonProperty("site_id")
  private String siteId = null;

  @JsonProperty("resource")
  private String resource = null;

  @JsonProperty("resource_id")
  private String resourceId = null;

  @JsonProperty("status")
  private String status = null;

  @JsonProperty("moderation")
  private MessageModeration moderation = null;

  public Message messageId(String messageId) {
    this.messageId = messageId;
    return this;
  }

   /**
   * Get messageId
   * @return messageId
  **/
  @ApiModelProperty(value = "")
  public String getMessageId() {
    return messageId;
  }

  public void setMessageId(String messageId) {
    this.messageId = messageId;
  }

  public Message dateReceived(String dateReceived) {
    this.dateReceived = dateReceived;
    return this;
  }

   /**
   * Get dateReceived
   * @return dateReceived
  **/
  @ApiModelProperty(value = "")
  public String getDateReceived() {
    return dateReceived;
  }

  public void setDateReceived(String dateReceived) {
    this.dateReceived = dateReceived;
  }

  public Message date(String date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @ApiModelProperty(value = "")
  public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }

  public Message dateAvailable(String dateAvailable) {
    this.dateAvailable = dateAvailable;
    return this;
  }

   /**
   * Get dateAvailable
   * @return dateAvailable
  **/
  @ApiModelProperty(value = "")
  public String getDateAvailable() {
    return dateAvailable;
  }

  public void setDateAvailable(String dateAvailable) {
    this.dateAvailable = dateAvailable;
  }

  public Message dateNotified(String dateNotified) {
    this.dateNotified = dateNotified;
    return this;
  }

   /**
   * Get dateNotified
   * @return dateNotified
  **/
  @ApiModelProperty(value = "")
  public String getDateNotified() {
    return dateNotified;
  }

  public void setDateNotified(String dateNotified) {
    this.dateNotified = dateNotified;
  }

  public Message dateRead(String dateRead) {
    this.dateRead = dateRead;
    return this;
  }

   /**
   * Get dateRead
   * @return dateRead
  **/
  @ApiModelProperty(value = "")
  public String getDateRead() {
    return dateRead;
  }

  public void setDateRead(String dateRead) {
    this.dateRead = dateRead;
  }

  public Message from(MessageFrom from) {
    this.from = from;
    return this;
  }

   /**
   * Get from
   * @return from
  **/
  @ApiModelProperty(value = "")
  public MessageFrom getFrom() {
    return from;
  }

  public void setFrom(MessageFrom from) {
    this.from = from;
  }

  public Message to(List<MessageTo> to) {
    this.to = to;
    return this;
  }

  public Message addToItem(MessageTo toItem) {
    if (this.to == null) {
      this.to = new ArrayList<MessageTo>();
    }
    this.to.add(toItem);
    return this;
  }

   /**
   * Get to
   * @return to
  **/
  @ApiModelProperty(value = "")
  public List<MessageTo> getTo() {
    return to;
  }

  public void setTo(List<MessageTo> to) {
    this.to = to;
  }

  public Message subject(String subject) {
    this.subject = subject;
    return this;
  }

   /**
   * Get subject
   * @return subject
  **/
  @ApiModelProperty(value = "")
  public String getSubject() {
    return subject;
  }

  public void setSubject(String subject) {
    this.subject = subject;
  }

  public Message text(MessageText text) {
    this.text = text;
    return this;
  }

   /**
   * Get text
   * @return text
  **/
  @ApiModelProperty(value = "")
  public MessageText getText() {
    return text;
  }

  public void setText(MessageText text) {
    this.text = text;
  }

  public Message attachments(List<String> attachments) {
    this.attachments = attachments;
    return this;
  }

  public Message addAttachmentsItem(String attachmentsItem) {
    if (this.attachments == null) {
      this.attachments = new ArrayList<String>();
    }
    this.attachments.add(attachmentsItem);
    return this;
  }

   /**
   * Get attachments
   * @return attachments
  **/
  @ApiModelProperty(value = "")
  public List<String> getAttachments() {
    return attachments;
  }

  public void setAttachments(List<String> attachments) {
    this.attachments = attachments;
  }

  public Message attachmentsValidations(List<MessageAttachmentsValidations> attachmentsValidations) {
    this.attachmentsValidations = attachmentsValidations;
    return this;
  }

  public Message addAttachmentsValidationsItem(MessageAttachmentsValidations attachmentsValidationsItem) {
    if (this.attachmentsValidations == null) {
      this.attachmentsValidations = new ArrayList<MessageAttachmentsValidations>();
    }
    this.attachmentsValidations.add(attachmentsValidationsItem);
    return this;
  }

   /**
   * Get attachmentsValidations
   * @return attachmentsValidations
  **/
  @ApiModelProperty(value = "")
  public List<MessageAttachmentsValidations> getAttachmentsValidations() {
    return attachmentsValidations;
  }

  public void setAttachmentsValidations(List<MessageAttachmentsValidations> attachmentsValidations) {
    this.attachmentsValidations = attachmentsValidations;
  }

  public Message siteId(String siteId) {
    this.siteId = siteId;
    return this;
  }

   /**
   * Get siteId
   * @return siteId
  **/
  @ApiModelProperty(value = "")
  public String getSiteId() {
    return siteId;
  }

  public void setSiteId(String siteId) {
    this.siteId = siteId;
  }

  public Message resource(String resource) {
    this.resource = resource;
    return this;
  }

   /**
   * Get resource
   * @return resource
  **/
  @ApiModelProperty(value = "")
  public String getResource() {
    return resource;
  }

  public void setResource(String resource) {
    this.resource = resource;
  }

  public Message resourceId(String resourceId) {
    this.resourceId = resourceId;
    return this;
  }

   /**
   * Get resourceId
   * @return resourceId
  **/
  @ApiModelProperty(value = "")
  public String getResourceId() {
    return resourceId;
  }

  public void setResourceId(String resourceId) {
    this.resourceId = resourceId;
  }

  public Message status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public Message moderation(MessageModeration moderation) {
    this.moderation = moderation;
    return this;
  }

   /**
   * Get moderation
   * @return moderation
  **/
  @ApiModelProperty(value = "")
  public MessageModeration getModeration() {
    return moderation;
  }

  public void setModeration(MessageModeration moderation) {
    this.moderation = moderation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Message message = (Message) o;
    return Objects.equals(this.messageId, message.messageId) &&
        Objects.equals(this.dateReceived, message.dateReceived) &&
        Objects.equals(this.date, message.date) &&
        Objects.equals(this.dateAvailable, message.dateAvailable) &&
        Objects.equals(this.dateNotified, message.dateNotified) &&
        Objects.equals(this.dateRead, message.dateRead) &&
        Objects.equals(this.from, message.from) &&
        Objects.equals(this.to, message.to) &&
        Objects.equals(this.subject, message.subject) &&
        Objects.equals(this.text, message.text) &&
        Objects.equals(this.attachments, message.attachments) &&
        Objects.equals(this.attachmentsValidations, message.attachmentsValidations) &&
        Objects.equals(this.siteId, message.siteId) &&
        Objects.equals(this.resource, message.resource) &&
        Objects.equals(this.resourceId, message.resourceId) &&
        Objects.equals(this.status, message.status) &&
        Objects.equals(this.moderation, message.moderation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(messageId, dateReceived, date, dateAvailable, dateNotified, dateRead, from, to, subject, text, attachments, attachmentsValidations, siteId, resource, resourceId, status, moderation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Message {\n");
    
    sb.append("    messageId: ").append(toIndentedString(messageId)).append("\n");
    sb.append("    dateReceived: ").append(toIndentedString(dateReceived)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    dateAvailable: ").append(toIndentedString(dateAvailable)).append("\n");
    sb.append("    dateNotified: ").append(toIndentedString(dateNotified)).append("\n");
    sb.append("    dateRead: ").append(toIndentedString(dateRead)).append("\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    attachments: ").append(toIndentedString(attachments)).append("\n");
    sb.append("    attachmentsValidations: ").append(toIndentedString(attachmentsValidations)).append("\n");
    sb.append("    siteId: ").append(toIndentedString(siteId)).append("\n");
    sb.append("    resource: ").append(toIndentedString(resource)).append("\n");
    sb.append("    resourceId: ").append(toIndentedString(resourceId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    moderation: ").append(toIndentedString(moderation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

