/*
 * MercadoLibre API
 * MercadoLibre API Documentation.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Claims;
import io.swagger.client.model.DelayedHandlingTime;
import io.swagger.client.model.Sales;

/**
 * Metrics
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-08-06T14:21:46.668-03:00")
public class Metrics {
  @JsonProperty("sales")
  private Sales sales = null;

  @JsonProperty("claims")
  private Claims claims = null;

  @JsonProperty("delayed_handling_time")
  private DelayedHandlingTime delayedHandlingTime = null;

  public Metrics sales(Sales sales) {
    this.sales = sales;
    return this;
  }

   /**
   * Get sales
   * @return sales
  **/
  @ApiModelProperty(value = "")
  public Sales getSales() {
    return sales;
  }

  public void setSales(Sales sales) {
    this.sales = sales;
  }

  public Metrics claims(Claims claims) {
    this.claims = claims;
    return this;
  }

   /**
   * Get claims
   * @return claims
  **/
  @ApiModelProperty(value = "")
  public Claims getClaims() {
    return claims;
  }

  public void setClaims(Claims claims) {
    this.claims = claims;
  }

  public Metrics delayedHandlingTime(DelayedHandlingTime delayedHandlingTime) {
    this.delayedHandlingTime = delayedHandlingTime;
    return this;
  }

   /**
   * Get delayedHandlingTime
   * @return delayedHandlingTime
  **/
  @ApiModelProperty(value = "")
  public DelayedHandlingTime getDelayedHandlingTime() {
    return delayedHandlingTime;
  }

  public void setDelayedHandlingTime(DelayedHandlingTime delayedHandlingTime) {
    this.delayedHandlingTime = delayedHandlingTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Metrics metrics = (Metrics) o;
    return Objects.equals(this.sales, metrics.sales) &&
        Objects.equals(this.claims, metrics.claims) &&
        Objects.equals(this.delayedHandlingTime, metrics.delayedHandlingTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sales, claims, delayedHandlingTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Metrics {\n");
    
    sb.append("    sales: ").append(toIndentedString(sales)).append("\n");
    sb.append("    claims: ").append(toIndentedString(claims)).append("\n");
    sb.append("    delayedHandlingTime: ").append(toIndentedString(delayedHandlingTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

