/*
 * MercadoLibre API
 * MercadoLibre API Documentation.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ReceiverAddressCity;
import io.swagger.client.model.ReceiverAddressCountry;
import io.swagger.client.model.ReceiverAddressMunicipality;
import io.swagger.client.model.ReceiverAddressNeighborhood;
import io.swagger.client.model.ReceiverAddressState;
import java.util.ArrayList;
import java.util.List;

/**
 * ReceiverAddress
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-08-06T14:21:46.668-03:00")
public class ReceiverAddress {
  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("address_line")
  private String addressLine = null;

  @JsonProperty("street_name")
  private String streetName = null;

  @JsonProperty("street_number")
  private String streetNumber = null;

  @JsonProperty("comment")
  private String comment = null;

  @JsonProperty("zip_code")
  private String zipCode = null;

  @JsonProperty("city")
  private ReceiverAddressCity city = null;

  @JsonProperty("state")
  private ReceiverAddressState state = null;

  @JsonProperty("country")
  private ReceiverAddressCountry country = null;

  @JsonProperty("neighborhood")
  private ReceiverAddressNeighborhood neighborhood = null;

  @JsonProperty("municipality")
  private ReceiverAddressMunicipality municipality = null;

  @JsonProperty("agency")
  private Object agency = null;

  @JsonProperty("types")
  private List<String> types = null;

  @JsonProperty("latitude")
  private Double latitude = null;

  @JsonProperty("longitude")
  private Double longitude = null;

  @JsonProperty("geolocation_type")
  private String geolocationType = null;

  @JsonProperty("receiver_name")
  private String receiverName = null;

  @JsonProperty("receiver_phone")
  private String receiverPhone = null;

  public ReceiverAddress id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public ReceiverAddress addressLine(String addressLine) {
    this.addressLine = addressLine;
    return this;
  }

   /**
   * Get addressLine
   * @return addressLine
  **/
  @ApiModelProperty(value = "")
  public String getAddressLine() {
    return addressLine;
  }

  public void setAddressLine(String addressLine) {
    this.addressLine = addressLine;
  }

  public ReceiverAddress streetName(String streetName) {
    this.streetName = streetName;
    return this;
  }

   /**
   * Get streetName
   * @return streetName
  **/
  @ApiModelProperty(value = "")
  public String getStreetName() {
    return streetName;
  }

  public void setStreetName(String streetName) {
    this.streetName = streetName;
  }

  public ReceiverAddress streetNumber(String streetNumber) {
    this.streetNumber = streetNumber;
    return this;
  }

   /**
   * Get streetNumber
   * @return streetNumber
  **/
  @ApiModelProperty(value = "")
  public String getStreetNumber() {
    return streetNumber;
  }

  public void setStreetNumber(String streetNumber) {
    this.streetNumber = streetNumber;
  }

  public ReceiverAddress comment(String comment) {
    this.comment = comment;
    return this;
  }

   /**
   * Get comment
   * @return comment
  **/
  @ApiModelProperty(value = "")
  public String getComment() {
    return comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }

  public ReceiverAddress zipCode(String zipCode) {
    this.zipCode = zipCode;
    return this;
  }

   /**
   * Get zipCode
   * @return zipCode
  **/
  @ApiModelProperty(value = "")
  public String getZipCode() {
    return zipCode;
  }

  public void setZipCode(String zipCode) {
    this.zipCode = zipCode;
  }

  public ReceiverAddress city(ReceiverAddressCity city) {
    this.city = city;
    return this;
  }

   /**
   * Get city
   * @return city
  **/
  @ApiModelProperty(value = "")
  public ReceiverAddressCity getCity() {
    return city;
  }

  public void setCity(ReceiverAddressCity city) {
    this.city = city;
  }

  public ReceiverAddress state(ReceiverAddressState state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @ApiModelProperty(value = "")
  public ReceiverAddressState getState() {
    return state;
  }

  public void setState(ReceiverAddressState state) {
    this.state = state;
  }

  public ReceiverAddress country(ReceiverAddressCountry country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  @ApiModelProperty(value = "")
  public ReceiverAddressCountry getCountry() {
    return country;
  }

  public void setCountry(ReceiverAddressCountry country) {
    this.country = country;
  }

  public ReceiverAddress neighborhood(ReceiverAddressNeighborhood neighborhood) {
    this.neighborhood = neighborhood;
    return this;
  }

   /**
   * Get neighborhood
   * @return neighborhood
  **/
  @ApiModelProperty(value = "")
  public ReceiverAddressNeighborhood getNeighborhood() {
    return neighborhood;
  }

  public void setNeighborhood(ReceiverAddressNeighborhood neighborhood) {
    this.neighborhood = neighborhood;
  }

  public ReceiverAddress municipality(ReceiverAddressMunicipality municipality) {
    this.municipality = municipality;
    return this;
  }

   /**
   * Get municipality
   * @return municipality
  **/
  @ApiModelProperty(value = "")
  public ReceiverAddressMunicipality getMunicipality() {
    return municipality;
  }

  public void setMunicipality(ReceiverAddressMunicipality municipality) {
    this.municipality = municipality;
  }

  public ReceiverAddress agency(Object agency) {
    this.agency = agency;
    return this;
  }

   /**
   * Get agency
   * @return agency
  **/
  @ApiModelProperty(value = "")
  public Object getAgency() {
    return agency;
  }

  public void setAgency(Object agency) {
    this.agency = agency;
  }

  public ReceiverAddress types(List<String> types) {
    this.types = types;
    return this;
  }

  public ReceiverAddress addTypesItem(String typesItem) {
    if (this.types == null) {
      this.types = new ArrayList<String>();
    }
    this.types.add(typesItem);
    return this;
  }

   /**
   * Get types
   * @return types
  **/
  @ApiModelProperty(value = "")
  public List<String> getTypes() {
    return types;
  }

  public void setTypes(List<String> types) {
    this.types = types;
  }

  public ReceiverAddress latitude(Double latitude) {
    this.latitude = latitude;
    return this;
  }

   /**
   * Get latitude
   * @return latitude
  **/
  @ApiModelProperty(value = "")
  public Double getLatitude() {
    return latitude;
  }

  public void setLatitude(Double latitude) {
    this.latitude = latitude;
  }

  public ReceiverAddress longitude(Double longitude) {
    this.longitude = longitude;
    return this;
  }

   /**
   * Get longitude
   * @return longitude
  **/
  @ApiModelProperty(value = "")
  public Double getLongitude() {
    return longitude;
  }

  public void setLongitude(Double longitude) {
    this.longitude = longitude;
  }

  public ReceiverAddress geolocationType(String geolocationType) {
    this.geolocationType = geolocationType;
    return this;
  }

   /**
   * Get geolocationType
   * @return geolocationType
  **/
  @ApiModelProperty(value = "")
  public String getGeolocationType() {
    return geolocationType;
  }

  public void setGeolocationType(String geolocationType) {
    this.geolocationType = geolocationType;
  }

  public ReceiverAddress receiverName(String receiverName) {
    this.receiverName = receiverName;
    return this;
  }

   /**
   * Get receiverName
   * @return receiverName
  **/
  @ApiModelProperty(value = "")
  public String getReceiverName() {
    return receiverName;
  }

  public void setReceiverName(String receiverName) {
    this.receiverName = receiverName;
  }

  public ReceiverAddress receiverPhone(String receiverPhone) {
    this.receiverPhone = receiverPhone;
    return this;
  }

   /**
   * Get receiverPhone
   * @return receiverPhone
  **/
  @ApiModelProperty(value = "")
  public String getReceiverPhone() {
    return receiverPhone;
  }

  public void setReceiverPhone(String receiverPhone) {
    this.receiverPhone = receiverPhone;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReceiverAddress receiverAddress = (ReceiverAddress) o;
    return Objects.equals(this.id, receiverAddress.id) &&
        Objects.equals(this.addressLine, receiverAddress.addressLine) &&
        Objects.equals(this.streetName, receiverAddress.streetName) &&
        Objects.equals(this.streetNumber, receiverAddress.streetNumber) &&
        Objects.equals(this.comment, receiverAddress.comment) &&
        Objects.equals(this.zipCode, receiverAddress.zipCode) &&
        Objects.equals(this.city, receiverAddress.city) &&
        Objects.equals(this.state, receiverAddress.state) &&
        Objects.equals(this.country, receiverAddress.country) &&
        Objects.equals(this.neighborhood, receiverAddress.neighborhood) &&
        Objects.equals(this.municipality, receiverAddress.municipality) &&
        Objects.equals(this.agency, receiverAddress.agency) &&
        Objects.equals(this.types, receiverAddress.types) &&
        Objects.equals(this.latitude, receiverAddress.latitude) &&
        Objects.equals(this.longitude, receiverAddress.longitude) &&
        Objects.equals(this.geolocationType, receiverAddress.geolocationType) &&
        Objects.equals(this.receiverName, receiverAddress.receiverName) &&
        Objects.equals(this.receiverPhone, receiverAddress.receiverPhone);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, addressLine, streetName, streetNumber, comment, zipCode, city, state, country, neighborhood, municipality, agency, types, latitude, longitude, geolocationType, receiverName, receiverPhone);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReceiverAddress {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    addressLine: ").append(toIndentedString(addressLine)).append("\n");
    sb.append("    streetName: ").append(toIndentedString(streetName)).append("\n");
    sb.append("    streetNumber: ").append(toIndentedString(streetNumber)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    zipCode: ").append(toIndentedString(zipCode)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    neighborhood: ").append(toIndentedString(neighborhood)).append("\n");
    sb.append("    municipality: ").append(toIndentedString(municipality)).append("\n");
    sb.append("    agency: ").append(toIndentedString(agency)).append("\n");
    sb.append("    types: ").append(toIndentedString(types)).append("\n");
    sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
    sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
    sb.append("    geolocationType: ").append(toIndentedString(geolocationType)).append("\n");
    sb.append("    receiverName: ").append(toIndentedString(receiverName)).append("\n");
    sb.append("    receiverPhone: ").append(toIndentedString(receiverPhone)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

