/*
 * MercadoLibre API
 * MercadoLibre API Documentation.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * AttributeCombinations
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-08-06T14:21:46.668-03:00")
public class RefreshToken {

    @JsonProperty("access_token")
    private String access_token = null;

    @JsonProperty("token_type")
    private String token_type = null;

    @JsonProperty("expires_in")
    private Integer expires_in = null;

    @JsonProperty("refresh_token")
    private String refresh_token = null;

    @JsonProperty("user_id")
    private String user_id = null;

    @JsonProperty("scope")
    private String scope = null;

    public String getAccess_token() {
        return access_token;
    }

    public void setAccess_token(String access_token) {
        this.access_token = access_token;
    }

    public String getToken_type() {
        return token_type;
    }

    public void setToken_type(String token_type) {
        this.token_type = token_type;
    }

    public Integer getExpires_in() {
        return expires_in;
    }

    public void setExpires_in(Integer expires_in) {
        this.expires_in = expires_in;
    }

    public String getRefresh_token() {
        return refresh_token;
    }

    public void setRefresh_token(String refresh_token) {
        this.refresh_token = refresh_token;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }
    public String getScope() {
        return scope;
    }

    public void setScope(String scope) {
        this.scope = scope;
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class RefreshToken {\n");

        sb.append("    access_token: ").append(toIndentedString(access_token)).append("\n");
        sb.append("    token_type: ").append(toIndentedString(token_type)).append("\n");
        sb.append("    expires_in: ").append(toIndentedString(expires_in)).append("\n");
        sb.append("    user_id: ").append(toIndentedString(user_id)).append("\n");
        sb.append("    refresh_token: ").append(toIndentedString(refresh_token)).append("\n");
        sb.append("    scope: ").append(toIndentedString(scope)).append("\n");

        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */

    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        RefreshToken RefreshToken = (RefreshToken) o;

        if (access_token != null ? !access_token.equals(RefreshToken.access_token) : RefreshToken.access_token != null) return false;
        if (token_type != null ? !token_type.equals(RefreshToken.token_type) : RefreshToken.token_type != null) return false;
        if (expires_in != null ? !expires_in.equals(RefreshToken.expires_in) : RefreshToken.expires_in != null) return false;
        if (user_id != null ? !user_id.equals(RefreshToken.user_id) : RefreshToken.user_id != null) return false;
        if (refresh_token != null ? !refresh_token.equals(RefreshToken.refresh_token) : RefreshToken.refresh_token != null) {
            return false;
        }
        if (scope != null ? !scope.equals(RefreshToken.scope) : RefreshToken.scope != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = access_token != null ? access_token.hashCode() : 0;
        result = 31 * result + (token_type != null ? token_type.hashCode() : 0);
        result = 31 * result + (expires_in != null ? expires_in.hashCode() : 0);
        result = 31 * result + (refresh_token != null ? refresh_token.hashCode() : 0);
        result = 31 * result + (user_id != null ? user_id.hashCode() : 0);
        result = 31 * result + (scope != null ? scope.hashCode() : 0);
        return result;
    }
}

