/*
 * MercadoLibre API
 * MercadoLibre API Documentation.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Neighborhood;
import io.swagger.client.model.SearchLocationCity;
import io.swagger.client.model.SearchLocationState;

/**
 * SearchLocation
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-08-06T14:21:46.668-03:00")
public class SearchLocation {
  @JsonProperty("neighborhood")
  private Neighborhood neighborhood = null;

  @JsonProperty("city")
  private SearchLocationCity city = null;

  @JsonProperty("state")
  private SearchLocationState state = null;

  public SearchLocation neighborhood(Neighborhood neighborhood) {
    this.neighborhood = neighborhood;
    return this;
  }

   /**
   * Get neighborhood
   * @return neighborhood
  **/
  @ApiModelProperty(value = "")
  public Neighborhood getNeighborhood() {
    return neighborhood;
  }

  public void setNeighborhood(Neighborhood neighborhood) {
    this.neighborhood = neighborhood;
  }

  public SearchLocation city(SearchLocationCity city) {
    this.city = city;
    return this;
  }

   /**
   * Get city
   * @return city
  **/
  @ApiModelProperty(value = "")
  public SearchLocationCity getCity() {
    return city;
  }

  public void setCity(SearchLocationCity city) {
    this.city = city;
  }

  public SearchLocation state(SearchLocationState state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @ApiModelProperty(value = "")
  public SearchLocationState getState() {
    return state;
  }

  public void setState(SearchLocationState state) {
    this.state = state;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchLocation searchLocation = (SearchLocation) o;
    return Objects.equals(this.neighborhood, searchLocation.neighborhood) &&
        Objects.equals(this.city, searchLocation.city) &&
        Objects.equals(this.state, searchLocation.state);
  }

  @Override
  public int hashCode() {
    return Objects.hash(neighborhood, city, state);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchLocation {\n");
    
    sb.append("    neighborhood: ").append(toIndentedString(neighborhood)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

