/*
 * MercadoLibre API
 * MercadoLibre API Documentation.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.CostComponents;
import io.swagger.client.model.ReceiverAddress;
import io.swagger.client.model.SenderAddress;
import io.swagger.client.model.ShippingItems;
import io.swagger.client.model.ShippingOption;
import io.swagger.client.model.StatusHistory;
import java.util.ArrayList;
import java.util.List;

/**
 * Shipment
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-08-06T14:21:46.668-03:00")
public class Shipment {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("mode")
  private String mode = null;

  @JsonProperty("created_by")
  private String createdBy = null;

  @JsonProperty("order_id")
  private Integer orderId = null;

  @JsonProperty("order_cost")
  private Integer orderCost = null;

  @JsonProperty("base_cost")
  private Object baseCost = null;

  @JsonProperty("site_id")
  private String siteId = null;

  @JsonProperty("status")
  private String status = null;

  @JsonProperty("substatus")
  private Object substatus = null;

  @JsonProperty("status_history")
  private StatusHistory statusHistory = null;

  @JsonProperty("date_created")
  private String dateCreated = null;

  @JsonProperty("last_updated")
  private String lastUpdated = null;

  @JsonProperty("tracking_number")
  private String trackingNumber = null;

  @JsonProperty("tracking_method")
  private String trackingMethod = null;

  @JsonProperty("service_id")
  private Integer serviceId = null;

  @JsonProperty("carrier_info")
  private Object carrierInfo = null;

  @JsonProperty("sender_id")
  private Integer senderId = null;

  @JsonProperty("sender_address")
  private SenderAddress senderAddress = null;

  @JsonProperty("receiver_id")
  private Integer receiverId = null;

  @JsonProperty("receiver_address")
  private ReceiverAddress receiverAddress = null;

  @JsonProperty("shipping_items")
  private List<ShippingItems> shippingItems = null;

  @JsonProperty("shipping_option")
  private ShippingOption shippingOption = null;

  @JsonProperty("comments")
  private Object comments = null;

  @JsonProperty("date_first_printed")
  private String dateFirstPrinted = null;

  @JsonProperty("market_place")
  private String marketPlace = null;

  @JsonProperty("return_details")
  private Object returnDetails = null;

  @JsonProperty("tags")
  private List<String> tags = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("application_id")
  private Object applicationId = null;

  @JsonProperty("return_tracking_number")
  private Object returnTrackingNumber = null;

  @JsonProperty("cost_components")
  private CostComponents costComponents = null;

  @JsonProperty("logistic_type")
  private String logisticType = null;

  @JsonProperty("substatus_history")
  private List<String> substatusHistory = null;

  @JsonProperty("delay")
  private List<String> delay = null;

  public Shipment id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Shipment mode(String mode) {
    this.mode = mode;
    return this;
  }

   /**
   * Get mode
   * @return mode
  **/
  @ApiModelProperty(value = "")
  public String getMode() {
    return mode;
  }

  public void setMode(String mode) {
    this.mode = mode;
  }

  public Shipment createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @ApiModelProperty(value = "")
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public Shipment orderId(Integer orderId) {
    this.orderId = orderId;
    return this;
  }

   /**
   * Get orderId
   * @return orderId
  **/
  @ApiModelProperty(value = "")
  public Integer getOrderId() {
    return orderId;
  }

  public void setOrderId(Integer orderId) {
    this.orderId = orderId;
  }

  public Shipment orderCost(Integer orderCost) {
    this.orderCost = orderCost;
    return this;
  }

   /**
   * Get orderCost
   * @return orderCost
  **/
  @ApiModelProperty(value = "")
  public Integer getOrderCost() {
    return orderCost;
  }

  public void setOrderCost(Integer orderCost) {
    this.orderCost = orderCost;
  }

  public Shipment baseCost(Object baseCost) {
    this.baseCost = baseCost;
    return this;
  }

   /**
   * Get baseCost
   * @return baseCost
  **/
  @ApiModelProperty(value = "")
  public Object getBaseCost() {
    return baseCost;
  }

  public void setBaseCost(Object baseCost) {
    this.baseCost = baseCost;
  }

  public Shipment siteId(String siteId) {
    this.siteId = siteId;
    return this;
  }

   /**
   * Get siteId
   * @return siteId
  **/
  @ApiModelProperty(value = "")
  public String getSiteId() {
    return siteId;
  }

  public void setSiteId(String siteId) {
    this.siteId = siteId;
  }

  public Shipment status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public Shipment substatus(Object substatus) {
    this.substatus = substatus;
    return this;
  }

   /**
   * Get substatus
   * @return substatus
  **/
  @ApiModelProperty(value = "")
  public Object getSubstatus() {
    return substatus;
  }

  public void setSubstatus(Object substatus) {
    this.substatus = substatus;
  }

  public Shipment statusHistory(StatusHistory statusHistory) {
    this.statusHistory = statusHistory;
    return this;
  }

   /**
   * Get statusHistory
   * @return statusHistory
  **/
  @ApiModelProperty(value = "")
  public StatusHistory getStatusHistory() {
    return statusHistory;
  }

  public void setStatusHistory(StatusHistory statusHistory) {
    this.statusHistory = statusHistory;
  }

  public Shipment dateCreated(String dateCreated) {
    this.dateCreated = dateCreated;
    return this;
  }

   /**
   * Get dateCreated
   * @return dateCreated
  **/
  @ApiModelProperty(value = "")
  public String getDateCreated() {
    return dateCreated;
  }

  public void setDateCreated(String dateCreated) {
    this.dateCreated = dateCreated;
  }

  public Shipment lastUpdated(String lastUpdated) {
    this.lastUpdated = lastUpdated;
    return this;
  }

   /**
   * Get lastUpdated
   * @return lastUpdated
  **/
  @ApiModelProperty(value = "")
  public String getLastUpdated() {
    return lastUpdated;
  }

  public void setLastUpdated(String lastUpdated) {
    this.lastUpdated = lastUpdated;
  }

  public Shipment trackingNumber(String trackingNumber) {
    this.trackingNumber = trackingNumber;
    return this;
  }

   /**
   * Get trackingNumber
   * @return trackingNumber
  **/
  @ApiModelProperty(value = "")
  public String getTrackingNumber() {
    return trackingNumber;
  }

  public void setTrackingNumber(String trackingNumber) {
    this.trackingNumber = trackingNumber;
  }

  public Shipment trackingMethod(String trackingMethod) {
    this.trackingMethod = trackingMethod;
    return this;
  }

   /**
   * Get trackingMethod
   * @return trackingMethod
  **/
  @ApiModelProperty(value = "")
  public String getTrackingMethod() {
    return trackingMethod;
  }

  public void setTrackingMethod(String trackingMethod) {
    this.trackingMethod = trackingMethod;
  }

  public Shipment serviceId(Integer serviceId) {
    this.serviceId = serviceId;
    return this;
  }

   /**
   * Get serviceId
   * @return serviceId
  **/
  @ApiModelProperty(value = "")
  public Integer getServiceId() {
    return serviceId;
  }

  public void setServiceId(Integer serviceId) {
    this.serviceId = serviceId;
  }

  public Shipment carrierInfo(Object carrierInfo) {
    this.carrierInfo = carrierInfo;
    return this;
  }

   /**
   * Get carrierInfo
   * @return carrierInfo
  **/
  @ApiModelProperty(value = "")
  public Object getCarrierInfo() {
    return carrierInfo;
  }

  public void setCarrierInfo(Object carrierInfo) {
    this.carrierInfo = carrierInfo;
  }

  public Shipment senderId(Integer senderId) {
    this.senderId = senderId;
    return this;
  }

   /**
   * Get senderId
   * @return senderId
  **/
  @ApiModelProperty(value = "")
  public Integer getSenderId() {
    return senderId;
  }

  public void setSenderId(Integer senderId) {
    this.senderId = senderId;
  }

  public Shipment senderAddress(SenderAddress senderAddress) {
    this.senderAddress = senderAddress;
    return this;
  }

   /**
   * Get senderAddress
   * @return senderAddress
  **/
  @ApiModelProperty(value = "")
  public SenderAddress getSenderAddress() {
    return senderAddress;
  }

  public void setSenderAddress(SenderAddress senderAddress) {
    this.senderAddress = senderAddress;
  }

  public Shipment receiverId(Integer receiverId) {
    this.receiverId = receiverId;
    return this;
  }

   /**
   * Get receiverId
   * @return receiverId
  **/
  @ApiModelProperty(value = "")
  public Integer getReceiverId() {
    return receiverId;
  }

  public void setReceiverId(Integer receiverId) {
    this.receiverId = receiverId;
  }

  public Shipment receiverAddress(ReceiverAddress receiverAddress) {
    this.receiverAddress = receiverAddress;
    return this;
  }

   /**
   * Get receiverAddress
   * @return receiverAddress
  **/
  @ApiModelProperty(value = "")
  public ReceiverAddress getReceiverAddress() {
    return receiverAddress;
  }

  public void setReceiverAddress(ReceiverAddress receiverAddress) {
    this.receiverAddress = receiverAddress;
  }

  public Shipment shippingItems(List<ShippingItems> shippingItems) {
    this.shippingItems = shippingItems;
    return this;
  }

  public Shipment addShippingItemsItem(ShippingItems shippingItemsItem) {
    if (this.shippingItems == null) {
      this.shippingItems = new ArrayList<ShippingItems>();
    }
    this.shippingItems.add(shippingItemsItem);
    return this;
  }

   /**
   * Get shippingItems
   * @return shippingItems
  **/
  @ApiModelProperty(value = "")
  public List<ShippingItems> getShippingItems() {
    return shippingItems;
  }

  public void setShippingItems(List<ShippingItems> shippingItems) {
    this.shippingItems = shippingItems;
  }

  public Shipment shippingOption(ShippingOption shippingOption) {
    this.shippingOption = shippingOption;
    return this;
  }

   /**
   * Get shippingOption
   * @return shippingOption
  **/
  @ApiModelProperty(value = "")
  public ShippingOption getShippingOption() {
    return shippingOption;
  }

  public void setShippingOption(ShippingOption shippingOption) {
    this.shippingOption = shippingOption;
  }

  public Shipment comments(Object comments) {
    this.comments = comments;
    return this;
  }

   /**
   * Get comments
   * @return comments
  **/
  @ApiModelProperty(value = "")
  public Object getComments() {
    return comments;
  }

  public void setComments(Object comments) {
    this.comments = comments;
  }

  public Shipment dateFirstPrinted(String dateFirstPrinted) {
    this.dateFirstPrinted = dateFirstPrinted;
    return this;
  }

   /**
   * Get dateFirstPrinted
   * @return dateFirstPrinted
  **/
  @ApiModelProperty(value = "")
  public String getDateFirstPrinted() {
    return dateFirstPrinted;
  }

  public void setDateFirstPrinted(String dateFirstPrinted) {
    this.dateFirstPrinted = dateFirstPrinted;
  }

  public Shipment marketPlace(String marketPlace) {
    this.marketPlace = marketPlace;
    return this;
  }

   /**
   * Get marketPlace
   * @return marketPlace
  **/
  @ApiModelProperty(value = "")
  public String getMarketPlace() {
    return marketPlace;
  }

  public void setMarketPlace(String marketPlace) {
    this.marketPlace = marketPlace;
  }

  public Shipment returnDetails(Object returnDetails) {
    this.returnDetails = returnDetails;
    return this;
  }

   /**
   * Get returnDetails
   * @return returnDetails
  **/
  @ApiModelProperty(value = "")
  public Object getReturnDetails() {
    return returnDetails;
  }

  public void setReturnDetails(Object returnDetails) {
    this.returnDetails = returnDetails;
  }

  public Shipment tags(List<String> tags) {
    this.tags = tags;
    return this;
  }

  public Shipment addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<String>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @ApiModelProperty(value = "")
  public List<String> getTags() {
    return tags;
  }

  public void setTags(List<String> tags) {
    this.tags = tags;
  }

  public Shipment type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Shipment applicationId(Object applicationId) {
    this.applicationId = applicationId;
    return this;
  }

   /**
   * Get applicationId
   * @return applicationId
  **/
  @ApiModelProperty(value = "")
  public Object getApplicationId() {
    return applicationId;
  }

  public void setApplicationId(Object applicationId) {
    this.applicationId = applicationId;
  }

  public Shipment returnTrackingNumber(Object returnTrackingNumber) {
    this.returnTrackingNumber = returnTrackingNumber;
    return this;
  }

   /**
   * Get returnTrackingNumber
   * @return returnTrackingNumber
  **/
  @ApiModelProperty(value = "")
  public Object getReturnTrackingNumber() {
    return returnTrackingNumber;
  }

  public void setReturnTrackingNumber(Object returnTrackingNumber) {
    this.returnTrackingNumber = returnTrackingNumber;
  }

  public Shipment costComponents(CostComponents costComponents) {
    this.costComponents = costComponents;
    return this;
  }

   /**
   * Get costComponents
   * @return costComponents
  **/
  @ApiModelProperty(value = "")
  public CostComponents getCostComponents() {
    return costComponents;
  }

  public void setCostComponents(CostComponents costComponents) {
    this.costComponents = costComponents;
  }

  public Shipment logisticType(String logisticType) {
    this.logisticType = logisticType;
    return this;
  }

   /**
   * Get logisticType
   * @return logisticType
  **/
  @ApiModelProperty(value = "")
  public String getLogisticType() {
    return logisticType;
  }

  public void setLogisticType(String logisticType) {
    this.logisticType = logisticType;
  }

  public Shipment substatusHistory(List<String> substatusHistory) {
    this.substatusHistory = substatusHistory;
    return this;
  }

  public Shipment addSubstatusHistoryItem(String substatusHistoryItem) {
    if (this.substatusHistory == null) {
      this.substatusHistory = new ArrayList<String>();
    }
    this.substatusHistory.add(substatusHistoryItem);
    return this;
  }

   /**
   * Get substatusHistory
   * @return substatusHistory
  **/
  @ApiModelProperty(value = "")
  public List<String> getSubstatusHistory() {
    return substatusHistory;
  }

  public void setSubstatusHistory(List<String> substatusHistory) {
    this.substatusHistory = substatusHistory;
  }

  public Shipment delay(List<String> delay) {
    this.delay = delay;
    return this;
  }

  public Shipment addDelayItem(String delayItem) {
    if (this.delay == null) {
      this.delay = new ArrayList<String>();
    }
    this.delay.add(delayItem);
    return this;
  }

   /**
   * Get delay
   * @return delay
  **/
  @ApiModelProperty(value = "")
  public List<String> getDelay() {
    return delay;
  }

  public void setDelay(List<String> delay) {
    this.delay = delay;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Shipment shipment = (Shipment) o;
    return Objects.equals(this.id, shipment.id) &&
        Objects.equals(this.mode, shipment.mode) &&
        Objects.equals(this.createdBy, shipment.createdBy) &&
        Objects.equals(this.orderId, shipment.orderId) &&
        Objects.equals(this.orderCost, shipment.orderCost) &&
        Objects.equals(this.baseCost, shipment.baseCost) &&
        Objects.equals(this.siteId, shipment.siteId) &&
        Objects.equals(this.status, shipment.status) &&
        Objects.equals(this.substatus, shipment.substatus) &&
        Objects.equals(this.statusHistory, shipment.statusHistory) &&
        Objects.equals(this.dateCreated, shipment.dateCreated) &&
        Objects.equals(this.lastUpdated, shipment.lastUpdated) &&
        Objects.equals(this.trackingNumber, shipment.trackingNumber) &&
        Objects.equals(this.trackingMethod, shipment.trackingMethod) &&
        Objects.equals(this.serviceId, shipment.serviceId) &&
        Objects.equals(this.carrierInfo, shipment.carrierInfo) &&
        Objects.equals(this.senderId, shipment.senderId) &&
        Objects.equals(this.senderAddress, shipment.senderAddress) &&
        Objects.equals(this.receiverId, shipment.receiverId) &&
        Objects.equals(this.receiverAddress, shipment.receiverAddress) &&
        Objects.equals(this.shippingItems, shipment.shippingItems) &&
        Objects.equals(this.shippingOption, shipment.shippingOption) &&
        Objects.equals(this.comments, shipment.comments) &&
        Objects.equals(this.dateFirstPrinted, shipment.dateFirstPrinted) &&
        Objects.equals(this.marketPlace, shipment.marketPlace) &&
        Objects.equals(this.returnDetails, shipment.returnDetails) &&
        Objects.equals(this.tags, shipment.tags) &&
        Objects.equals(this.type, shipment.type) &&
        Objects.equals(this.applicationId, shipment.applicationId) &&
        Objects.equals(this.returnTrackingNumber, shipment.returnTrackingNumber) &&
        Objects.equals(this.costComponents, shipment.costComponents) &&
        Objects.equals(this.logisticType, shipment.logisticType) &&
        Objects.equals(this.substatusHistory, shipment.substatusHistory) &&
        Objects.equals(this.delay, shipment.delay);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, mode, createdBy, orderId, orderCost, baseCost, siteId, status, substatus, statusHistory, dateCreated, lastUpdated, trackingNumber, trackingMethod, serviceId, carrierInfo, senderId, senderAddress, receiverId, receiverAddress, shippingItems, shippingOption, comments, dateFirstPrinted, marketPlace, returnDetails, tags, type, applicationId, returnTrackingNumber, costComponents, logisticType, substatusHistory, delay);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Shipment {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    orderCost: ").append(toIndentedString(orderCost)).append("\n");
    sb.append("    baseCost: ").append(toIndentedString(baseCost)).append("\n");
    sb.append("    siteId: ").append(toIndentedString(siteId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    substatus: ").append(toIndentedString(substatus)).append("\n");
    sb.append("    statusHistory: ").append(toIndentedString(statusHistory)).append("\n");
    sb.append("    dateCreated: ").append(toIndentedString(dateCreated)).append("\n");
    sb.append("    lastUpdated: ").append(toIndentedString(lastUpdated)).append("\n");
    sb.append("    trackingNumber: ").append(toIndentedString(trackingNumber)).append("\n");
    sb.append("    trackingMethod: ").append(toIndentedString(trackingMethod)).append("\n");
    sb.append("    serviceId: ").append(toIndentedString(serviceId)).append("\n");
    sb.append("    carrierInfo: ").append(toIndentedString(carrierInfo)).append("\n");
    sb.append("    senderId: ").append(toIndentedString(senderId)).append("\n");
    sb.append("    senderAddress: ").append(toIndentedString(senderAddress)).append("\n");
    sb.append("    receiverId: ").append(toIndentedString(receiverId)).append("\n");
    sb.append("    receiverAddress: ").append(toIndentedString(receiverAddress)).append("\n");
    sb.append("    shippingItems: ").append(toIndentedString(shippingItems)).append("\n");
    sb.append("    shippingOption: ").append(toIndentedString(shippingOption)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    dateFirstPrinted: ").append(toIndentedString(dateFirstPrinted)).append("\n");
    sb.append("    marketPlace: ").append(toIndentedString(marketPlace)).append("\n");
    sb.append("    returnDetails: ").append(toIndentedString(returnDetails)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    applicationId: ").append(toIndentedString(applicationId)).append("\n");
    sb.append("    returnTrackingNumber: ").append(toIndentedString(returnTrackingNumber)).append("\n");
    sb.append("    costComponents: ").append(toIndentedString(costComponents)).append("\n");
    sb.append("    logisticType: ").append(toIndentedString(logisticType)).append("\n");
    sb.append("    substatusHistory: ").append(toIndentedString(substatusHistory)).append("\n");
    sb.append("    delay: ").append(toIndentedString(delay)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

