/*
 * MercadoLibre API
 * MercadoLibre API Documentation.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.EstimatedDeliveryExtended;
import io.swagger.client.model.EstimatedDeliveryFinal;
import io.swagger.client.model.EstimatedDeliveryLimit;
import io.swagger.client.model.EstimatedDeliveryTime;
import io.swagger.client.model.EstimatedHandlingLimit;
import io.swagger.client.model.EstimatedScheduleLimit;

/**
 * ShippingOption
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-08-06T14:21:46.668-03:00")
public class ShippingOption {
  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("shipping_method_id")
  private Integer shippingMethodId = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("currency_id")
  private String currencyId = null;

  @JsonProperty("cost")
  private Integer cost = null;

  @JsonProperty("delivery_type")
  private String deliveryType = null;

  @JsonProperty("list_cost")
  private Double listCost = null;

  @JsonProperty("estimated_delivery_time")
  private EstimatedDeliveryTime estimatedDeliveryTime = null;

  @JsonProperty("estimated_schedule_limit")
  private EstimatedScheduleLimit estimatedScheduleLimit = null;

  @JsonProperty("estimated_handling_limit")
  private EstimatedHandlingLimit estimatedHandlingLimit = null;

  @JsonProperty("estimated_delivery_final")
  private EstimatedDeliveryFinal estimatedDeliveryFinal = null;

  @JsonProperty("estimated_delivery_limit")
  private EstimatedDeliveryLimit estimatedDeliveryLimit = null;

  @JsonProperty("estimated_delivery_extended")
  private EstimatedDeliveryExtended estimatedDeliveryExtended = null;

  public ShippingOption id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public ShippingOption shippingMethodId(Integer shippingMethodId) {
    this.shippingMethodId = shippingMethodId;
    return this;
  }

   /**
   * Get shippingMethodId
   * @return shippingMethodId
  **/
  @ApiModelProperty(value = "")
  public Integer getShippingMethodId() {
    return shippingMethodId;
  }

  public void setShippingMethodId(Integer shippingMethodId) {
    this.shippingMethodId = shippingMethodId;
  }

  public ShippingOption name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ShippingOption currencyId(String currencyId) {
    this.currencyId = currencyId;
    return this;
  }

   /**
   * Get currencyId
   * @return currencyId
  **/
  @ApiModelProperty(value = "")
  public String getCurrencyId() {
    return currencyId;
  }

  public void setCurrencyId(String currencyId) {
    this.currencyId = currencyId;
  }

  public ShippingOption cost(Integer cost) {
    this.cost = cost;
    return this;
  }

   /**
   * Get cost
   * @return cost
  **/
  @ApiModelProperty(value = "")
  public Integer getCost() {
    return cost;
  }

  public void setCost(Integer cost) {
    this.cost = cost;
  }

  public ShippingOption deliveryType(String deliveryType) {
    this.deliveryType = deliveryType;
    return this;
  }

   /**
   * Get deliveryType
   * @return deliveryType
  **/
  @ApiModelProperty(value = "")
  public String getDeliveryType() {
    return deliveryType;
  }

  public void setDeliveryType(String deliveryType) {
    this.deliveryType = deliveryType;
  }

  public ShippingOption listCost(Double listCost) {
    this.listCost = listCost;
    return this;
  }

   /**
   * Get listCost
   * @return listCost
  **/
  @ApiModelProperty(value = "")
  public Double getListCost() {
    return listCost;
  }

  public void setListCost(Double listCost) {
    this.listCost = listCost;
  }

  public ShippingOption estimatedDeliveryTime(EstimatedDeliveryTime estimatedDeliveryTime) {
    this.estimatedDeliveryTime = estimatedDeliveryTime;
    return this;
  }

   /**
   * Get estimatedDeliveryTime
   * @return estimatedDeliveryTime
  **/
  @ApiModelProperty(value = "")
  public EstimatedDeliveryTime getEstimatedDeliveryTime() {
    return estimatedDeliveryTime;
  }

  public void setEstimatedDeliveryTime(EstimatedDeliveryTime estimatedDeliveryTime) {
    this.estimatedDeliveryTime = estimatedDeliveryTime;
  }

  public ShippingOption estimatedScheduleLimit(EstimatedScheduleLimit estimatedScheduleLimit) {
    this.estimatedScheduleLimit = estimatedScheduleLimit;
    return this;
  }

   /**
   * Get estimatedScheduleLimit
   * @return estimatedScheduleLimit
  **/
  @ApiModelProperty(value = "")
  public EstimatedScheduleLimit getEstimatedScheduleLimit() {
    return estimatedScheduleLimit;
  }

  public void setEstimatedScheduleLimit(EstimatedScheduleLimit estimatedScheduleLimit) {
    this.estimatedScheduleLimit = estimatedScheduleLimit;
  }

  public ShippingOption estimatedHandlingLimit(EstimatedHandlingLimit estimatedHandlingLimit) {
    this.estimatedHandlingLimit = estimatedHandlingLimit;
    return this;
  }

   /**
   * Get estimatedHandlingLimit
   * @return estimatedHandlingLimit
  **/
  @ApiModelProperty(value = "")
  public EstimatedHandlingLimit getEstimatedHandlingLimit() {
    return estimatedHandlingLimit;
  }

  public void setEstimatedHandlingLimit(EstimatedHandlingLimit estimatedHandlingLimit) {
    this.estimatedHandlingLimit = estimatedHandlingLimit;
  }

  public ShippingOption estimatedDeliveryFinal(EstimatedDeliveryFinal estimatedDeliveryFinal) {
    this.estimatedDeliveryFinal = estimatedDeliveryFinal;
    return this;
  }

   /**
   * Get estimatedDeliveryFinal
   * @return estimatedDeliveryFinal
  **/
  @ApiModelProperty(value = "")
  public EstimatedDeliveryFinal getEstimatedDeliveryFinal() {
    return estimatedDeliveryFinal;
  }

  public void setEstimatedDeliveryFinal(EstimatedDeliveryFinal estimatedDeliveryFinal) {
    this.estimatedDeliveryFinal = estimatedDeliveryFinal;
  }

  public ShippingOption estimatedDeliveryLimit(EstimatedDeliveryLimit estimatedDeliveryLimit) {
    this.estimatedDeliveryLimit = estimatedDeliveryLimit;
    return this;
  }

   /**
   * Get estimatedDeliveryLimit
   * @return estimatedDeliveryLimit
  **/
  @ApiModelProperty(value = "")
  public EstimatedDeliveryLimit getEstimatedDeliveryLimit() {
    return estimatedDeliveryLimit;
  }

  public void setEstimatedDeliveryLimit(EstimatedDeliveryLimit estimatedDeliveryLimit) {
    this.estimatedDeliveryLimit = estimatedDeliveryLimit;
  }

  public ShippingOption estimatedDeliveryExtended(EstimatedDeliveryExtended estimatedDeliveryExtended) {
    this.estimatedDeliveryExtended = estimatedDeliveryExtended;
    return this;
  }

   /**
   * Get estimatedDeliveryExtended
   * @return estimatedDeliveryExtended
  **/
  @ApiModelProperty(value = "")
  public EstimatedDeliveryExtended getEstimatedDeliveryExtended() {
    return estimatedDeliveryExtended;
  }

  public void setEstimatedDeliveryExtended(EstimatedDeliveryExtended estimatedDeliveryExtended) {
    this.estimatedDeliveryExtended = estimatedDeliveryExtended;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShippingOption shippingOption = (ShippingOption) o;
    return Objects.equals(this.id, shippingOption.id) &&
        Objects.equals(this.shippingMethodId, shippingOption.shippingMethodId) &&
        Objects.equals(this.name, shippingOption.name) &&
        Objects.equals(this.currencyId, shippingOption.currencyId) &&
        Objects.equals(this.cost, shippingOption.cost) &&
        Objects.equals(this.deliveryType, shippingOption.deliveryType) &&
        Objects.equals(this.listCost, shippingOption.listCost) &&
        Objects.equals(this.estimatedDeliveryTime, shippingOption.estimatedDeliveryTime) &&
        Objects.equals(this.estimatedScheduleLimit, shippingOption.estimatedScheduleLimit) &&
        Objects.equals(this.estimatedHandlingLimit, shippingOption.estimatedHandlingLimit) &&
        Objects.equals(this.estimatedDeliveryFinal, shippingOption.estimatedDeliveryFinal) &&
        Objects.equals(this.estimatedDeliveryLimit, shippingOption.estimatedDeliveryLimit) &&
        Objects.equals(this.estimatedDeliveryExtended, shippingOption.estimatedDeliveryExtended);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, shippingMethodId, name, currencyId, cost, deliveryType, listCost, estimatedDeliveryTime, estimatedScheduleLimit, estimatedHandlingLimit, estimatedDeliveryFinal, estimatedDeliveryLimit, estimatedDeliveryExtended);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShippingOption {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    shippingMethodId: ").append(toIndentedString(shippingMethodId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    currencyId: ").append(toIndentedString(currencyId)).append("\n");
    sb.append("    cost: ").append(toIndentedString(cost)).append("\n");
    sb.append("    deliveryType: ").append(toIndentedString(deliveryType)).append("\n");
    sb.append("    listCost: ").append(toIndentedString(listCost)).append("\n");
    sb.append("    estimatedDeliveryTime: ").append(toIndentedString(estimatedDeliveryTime)).append("\n");
    sb.append("    estimatedScheduleLimit: ").append(toIndentedString(estimatedScheduleLimit)).append("\n");
    sb.append("    estimatedHandlingLimit: ").append(toIndentedString(estimatedHandlingLimit)).append("\n");
    sb.append("    estimatedDeliveryFinal: ").append(toIndentedString(estimatedDeliveryFinal)).append("\n");
    sb.append("    estimatedDeliveryLimit: ").append(toIndentedString(estimatedDeliveryLimit)).append("\n");
    sb.append("    estimatedDeliveryExtended: ").append(toIndentedString(estimatedDeliveryExtended)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

