/*
 * MercadoLibre API
 * MercadoLibre API Documentation.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.IdentificationTypesRules;
import java.util.ArrayList;
import java.util.List;

/**
 * SiteSettings
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-08-06T14:21:46.668-03:00")
public class SiteSettings {
  @JsonProperty("identification_types")
  private List<String> identificationTypes = null;

  @JsonProperty("taxpayer_types")
  private List<String> taxpayerTypes = null;

  @JsonProperty("identification_types_rules")
  private List<IdentificationTypesRules> identificationTypesRules = null;

  public SiteSettings identificationTypes(List<String> identificationTypes) {
    this.identificationTypes = identificationTypes;
    return this;
  }

  public SiteSettings addIdentificationTypesItem(String identificationTypesItem) {
    if (this.identificationTypes == null) {
      this.identificationTypes = new ArrayList<String>();
    }
    this.identificationTypes.add(identificationTypesItem);
    return this;
  }

   /**
   * Get identificationTypes
   * @return identificationTypes
  **/
  @ApiModelProperty(value = "")
  public List<String> getIdentificationTypes() {
    return identificationTypes;
  }

  public void setIdentificationTypes(List<String> identificationTypes) {
    this.identificationTypes = identificationTypes;
  }

  public SiteSettings taxpayerTypes(List<String> taxpayerTypes) {
    this.taxpayerTypes = taxpayerTypes;
    return this;
  }

  public SiteSettings addTaxpayerTypesItem(String taxpayerTypesItem) {
    if (this.taxpayerTypes == null) {
      this.taxpayerTypes = new ArrayList<String>();
    }
    this.taxpayerTypes.add(taxpayerTypesItem);
    return this;
  }

   /**
   * Get taxpayerTypes
   * @return taxpayerTypes
  **/
  @ApiModelProperty(value = "")
  public List<String> getTaxpayerTypes() {
    return taxpayerTypes;
  }

  public void setTaxpayerTypes(List<String> taxpayerTypes) {
    this.taxpayerTypes = taxpayerTypes;
  }

  public SiteSettings identificationTypesRules(List<IdentificationTypesRules> identificationTypesRules) {
    this.identificationTypesRules = identificationTypesRules;
    return this;
  }

  public SiteSettings addIdentificationTypesRulesItem(IdentificationTypesRules identificationTypesRulesItem) {
    if (this.identificationTypesRules == null) {
      this.identificationTypesRules = new ArrayList<IdentificationTypesRules>();
    }
    this.identificationTypesRules.add(identificationTypesRulesItem);
    return this;
  }

   /**
   * Get identificationTypesRules
   * @return identificationTypesRules
  **/
  @ApiModelProperty(value = "")
  public List<IdentificationTypesRules> getIdentificationTypesRules() {
    return identificationTypesRules;
  }

  public void setIdentificationTypesRules(List<IdentificationTypesRules> identificationTypesRules) {
    this.identificationTypesRules = identificationTypesRules;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SiteSettings siteSettings = (SiteSettings) o;
    return Objects.equals(this.identificationTypes, siteSettings.identificationTypes) &&
        Objects.equals(this.taxpayerTypes, siteSettings.taxpayerTypes) &&
        Objects.equals(this.identificationTypesRules, siteSettings.identificationTypesRules);
  }

  @Override
  public int hashCode() {
    return Objects.hash(identificationTypes, taxpayerTypes, identificationTypesRules);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SiteSettings {\n");
    
    sb.append("    identificationTypes: ").append(toIndentedString(identificationTypes)).append("\n");
    sb.append("    taxpayerTypes: ").append(toIndentedString(taxpayerTypes)).append("\n");
    sb.append("    identificationTypesRules: ").append(toIndentedString(identificationTypesRules)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

