/*
 * MercadoLibre API
 * MercadoLibre API Documentation.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * UserResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-08-06T14:21:46.668-03:00")
public class UserResponse {
  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("nickname")
  private String nickname = null;

  @JsonProperty("registration_date")
  private String registrationDate = null;

  @JsonProperty("first_name")
  private String firstName = null;

  @JsonProperty("last_name")
  private String lastName = null;

  @JsonProperty("gender")
  private String gender = null;

  @JsonProperty("country_id")
  private String countryId = null;

  @JsonProperty("email")
  private String email = null;

  @JsonProperty("identification")
  private Identification identification = null;

  @JsonProperty("address")
  private Address address = null;

  @JsonProperty("phone")
  private Phone phone = null;

  @JsonProperty("alternative_phone")
  private AlternativePhone alternativePhone = null;

  @JsonProperty("user_type")
  private String userType = null;

  @JsonProperty("tags")
  private List<String> tags = null;

  @JsonProperty("logo")
  private Object logo = null;

  @JsonProperty("points")
  private Integer points = null;

  @JsonProperty("site_id")
  private String siteId = null;

  @JsonProperty("permalink")
  private String permalink = null;

  @JsonProperty("shipping_modes")
  private List<String> shippingModes = null;

  @JsonProperty("seller_experience")
  private String sellerExperience = null;

  @JsonProperty("bill_data")
  private BillData billData = null;

  @JsonProperty("seller_reputation")
  private SellerReputation sellerReputation = null;

  @JsonProperty("buyer_reputation")
  private BuyerReputation buyerReputation = null;

  @JsonProperty("status")
  private Object status = null;

  @JsonProperty("secure_email")
  private String secureEmail = null;

  @JsonProperty("credit")
  private Credit credit = null;

  @JsonProperty("context")
  private Context context = null;

  public UserResponse id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public UserResponse nickname(String nickname) {
    this.nickname = nickname;
    return this;
  }

   /**
   * Get nickname
   * @return nickname
  **/
  @ApiModelProperty(value = "")
  public String getNickname() {
    return nickname;
  }

  public void setNickname(String nickname) {
    this.nickname = nickname;
  }

  public UserResponse registrationDate(String registrationDate) {
    this.registrationDate = registrationDate;
    return this;
  }

   /**
   * Get registrationDate
   * @return registrationDate
  **/
  @ApiModelProperty(value = "")
  public String getRegistrationDate() {
    return registrationDate;
  }

  public void setRegistrationDate(String registrationDate) {
    this.registrationDate = registrationDate;
  }

  public UserResponse firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * Get firstName
   * @return firstName
  **/
  @ApiModelProperty(value = "")
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public UserResponse lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/
  @ApiModelProperty(value = "")
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public UserResponse gender(String gender) {
    this.gender = gender;
    return this;
  }

   /**
   * Get gender
   * @return gender
  **/
  @ApiModelProperty(value = "")
  public String getGender() {
    return gender;
  }

  public void setGender(String gender) {
    this.gender = gender;
  }

  public UserResponse countryId(String countryId) {
    this.countryId = countryId;
    return this;
  }

   /**
   * Get countryId
   * @return countryId
  **/
  @ApiModelProperty(value = "")
  public String getCountryId() {
    return countryId;
  }

  public void setCountryId(String countryId) {
    this.countryId = countryId;
  }

  public UserResponse email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @ApiModelProperty(value = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public UserResponse identification(Identification identification) {
    this.identification = identification;
    return this;
  }

   /**
   * Get identification
   * @return identification
  **/
  @ApiModelProperty(value = "")
  public Identification getIdentification() {
    return identification;
  }

  public void setIdentification(Identification identification) {
    this.identification = identification;
  }

  public UserResponse address(Address address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @ApiModelProperty(value = "")
  public Address getAddress() {
    return address;
  }

  public void setAddress(Address address) {
    this.address = address;
  }

  public UserResponse phone(Phone phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  @ApiModelProperty(value = "")
  public Phone getPhone() {
    return phone;
  }

  public void setPhone(Phone phone) {
    this.phone = phone;
  }

  public UserResponse alternativePhone(AlternativePhone alternativePhone) {
    this.alternativePhone = alternativePhone;
    return this;
  }

   /**
   * Get alternativePhone
   * @return alternativePhone
  **/
  @ApiModelProperty(value = "")
  public AlternativePhone getAlternativePhone() {
    return alternativePhone;
  }

  public void setAlternativePhone(AlternativePhone alternativePhone) {
    this.alternativePhone = alternativePhone;
  }

  public UserResponse userType(String userType) {
    this.userType = userType;
    return this;
  }

   /**
   * Get userType
   * @return userType
  **/
  @ApiModelProperty(value = "")
  public String getUserType() {
    return userType;
  }

  public void setUserType(String userType) {
    this.userType = userType;
  }

  public UserResponse tags(List<String> tags) {
    this.tags = tags;
    return this;
  }

  public UserResponse addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<String>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @ApiModelProperty(value = "")
  public List<String> getTags() {
    return tags;
  }

  public void setTags(List<String> tags) {
    this.tags = tags;
  }

  public UserResponse logo(Object logo) {
    this.logo = logo;
    return this;
  }

   /**
   * Get logo
   * @return logo
  **/
  @ApiModelProperty(value = "")
  public Object getLogo() {
    return logo;
  }

  public void setLogo(Object logo) {
    this.logo = logo;
  }

  public UserResponse points(Integer points) {
    this.points = points;
    return this;
  }

   /**
   * Get points
   * @return points
  **/
  @ApiModelProperty(value = "")
  public Integer getPoints() {
    return points;
  }

  public void setPoints(Integer points) {
    this.points = points;
  }

  public UserResponse siteId(String siteId) {
    this.siteId = siteId;
    return this;
  }

   /**
   * Get siteId
   * @return siteId
  **/
  @ApiModelProperty(value = "")
  public String getSiteId() {
    return siteId;
  }

  public void setSiteId(String siteId) {
    this.siteId = siteId;
  }

  public UserResponse permalink(String permalink) {
    this.permalink = permalink;
    return this;
  }

   /**
   * Get permalink
   * @return permalink
  **/
  @ApiModelProperty(value = "")
  public String getPermalink() {
    return permalink;
  }

  public void setPermalink(String permalink) {
    this.permalink = permalink;
  }

  public UserResponse shippingModes(List<String> shippingModes) {
    this.shippingModes = shippingModes;
    return this;
  }

  public UserResponse addShippingModesItem(String shippingModesItem) {
    if (this.shippingModes == null) {
      this.shippingModes = new ArrayList<String>();
    }
    this.shippingModes.add(shippingModesItem);
    return this;
  }

   /**
   * Get shippingModes
   * @return shippingModes
  **/
  @ApiModelProperty(value = "")
  public List<String> getShippingModes() {
    return shippingModes;
  }

  public void setShippingModes(List<String> shippingModes) {
    this.shippingModes = shippingModes;
  }

  public UserResponse sellerExperience(String sellerExperience) {
    this.sellerExperience = sellerExperience;
    return this;
  }

   /**
   * Get sellerExperience
   * @return sellerExperience
  **/
  @ApiModelProperty(value = "")
  public String getSellerExperience() {
    return sellerExperience;
  }

  public void setSellerExperience(String sellerExperience) {
    this.sellerExperience = sellerExperience;
  }

  public UserResponse billData(BillData billData) {
    this.billData = billData;
    return this;
  }

   /**
   * Get billData
   * @return billData
  **/
  @ApiModelProperty(value = "")
  public BillData getBillData() {
    return billData;
  }

  public void setBillData(BillData billData) {
    this.billData = billData;
  }

  public UserResponse sellerReputation(SellerReputation sellerReputation) {
    this.sellerReputation = sellerReputation;
    return this;
  }

   /**
   * Get sellerReputation
   * @return sellerReputation
  **/
  @ApiModelProperty(value = "")
  public SellerReputation getSellerReputation() {
    return sellerReputation;
  }

  public void setSellerReputation(SellerReputation sellerReputation) {
    this.sellerReputation = sellerReputation;
  }

  public UserResponse buyerReputation(BuyerReputation buyerReputation) {
    this.buyerReputation = buyerReputation;
    return this;
  }

   /**
   * Get buyerReputation
   * @return buyerReputation
  **/
  @ApiModelProperty(value = "")
  public BuyerReputation getBuyerReputation() {
    return buyerReputation;
  }

  public void setBuyerReputation(BuyerReputation buyerReputation) {
    this.buyerReputation = buyerReputation;
  }

  public UserResponse status(Status status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public Object getStatus() {
    return status;
  }

  public void setStatus(Object status) {
    this.status = status;
  }

  public UserResponse secureEmail(String secureEmail) {
    this.secureEmail = secureEmail;
    return this;
  }

   /**
   * Get secureEmail
   * @return secureEmail
  **/
  @ApiModelProperty(value = "")
  public String getSecureEmail() {
    return secureEmail;
  }

  public void setSecureEmail(String secureEmail) {
    this.secureEmail = secureEmail;
  }

  public UserResponse credit(Credit credit) {
    this.credit = credit;
    return this;
  }

   /**
   * Get credit
   * @return credit
  **/
  @ApiModelProperty(value = "")
  public Credit getCredit() {
    return credit;
  }

  public void setCredit(Credit credit) {
    this.credit = credit;
  }

  public UserResponse context(Context context) {
    this.context = context;
    return this;
  }

   /**
   * Get context
   * @return context
  **/
  @ApiModelProperty(value = "")
  public Context getContext() {
    return context;
  }

  public void setContext(Context context) {
    this.context = context;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserResponse userResponse = (UserResponse) o;
    return Objects.equals(this.id, userResponse.id) &&
        Objects.equals(this.nickname, userResponse.nickname) &&
        Objects.equals(this.registrationDate, userResponse.registrationDate) &&
        Objects.equals(this.firstName, userResponse.firstName) &&
        Objects.equals(this.lastName, userResponse.lastName) &&
        Objects.equals(this.gender, userResponse.gender) &&
        Objects.equals(this.countryId, userResponse.countryId) &&
        Objects.equals(this.email, userResponse.email) &&
        Objects.equals(this.identification, userResponse.identification) &&
        Objects.equals(this.address, userResponse.address) &&
        Objects.equals(this.phone, userResponse.phone) &&
        Objects.equals(this.alternativePhone, userResponse.alternativePhone) &&
        Objects.equals(this.userType, userResponse.userType) &&
        Objects.equals(this.tags, userResponse.tags) &&
        Objects.equals(this.logo, userResponse.logo) &&
        Objects.equals(this.points, userResponse.points) &&
        Objects.equals(this.siteId, userResponse.siteId) &&
        Objects.equals(this.permalink, userResponse.permalink) &&
        Objects.equals(this.shippingModes, userResponse.shippingModes) &&
        Objects.equals(this.sellerExperience, userResponse.sellerExperience) &&
        Objects.equals(this.billData, userResponse.billData) &&
        Objects.equals(this.sellerReputation, userResponse.sellerReputation) &&
        Objects.equals(this.buyerReputation, userResponse.buyerReputation) &&
        Objects.equals(this.status, userResponse.status) &&
        Objects.equals(this.secureEmail, userResponse.secureEmail) &&
        Objects.equals(this.credit, userResponse.credit) &&
        Objects.equals(this.context, userResponse.context);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, nickname, registrationDate, firstName, lastName, gender, countryId, email, identification, address, phone, alternativePhone, userType, tags, logo, points, siteId, permalink, shippingModes, sellerExperience, billData, sellerReputation, buyerReputation, status, secureEmail, credit, context);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserResponse {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    nickname: ").append(toIndentedString(nickname)).append("\n");
    sb.append("    registrationDate: ").append(toIndentedString(registrationDate)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    countryId: ").append(toIndentedString(countryId)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    identification: ").append(toIndentedString(identification)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    alternativePhone: ").append(toIndentedString(alternativePhone)).append("\n");
    sb.append("    userType: ").append(toIndentedString(userType)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    logo: ").append(toIndentedString(logo)).append("\n");
    sb.append("    points: ").append(toIndentedString(points)).append("\n");
    sb.append("    siteId: ").append(toIndentedString(siteId)).append("\n");
    sb.append("    permalink: ").append(toIndentedString(permalink)).append("\n");
    sb.append("    shippingModes: ").append(toIndentedString(shippingModes)).append("\n");
    sb.append("    sellerExperience: ").append(toIndentedString(sellerExperience)).append("\n");
    sb.append("    billData: ").append(toIndentedString(billData)).append("\n");
    sb.append("    sellerReputation: ").append(toIndentedString(sellerReputation)).append("\n");
    sb.append("    buyerReputation: ").append(toIndentedString(buyerReputation)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    secureEmail: ").append(toIndentedString(secureEmail)).append("\n");
    sb.append("    credit: ").append(toIndentedString(credit)).append("\n");
    sb.append("    context: ").append(toIndentedString(context)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

