/*
 * MELI Markeplace SDK
 * This is a the codebase to generate a SDK for Open Platform Marketplace
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package meli_marketplace_lib;

import meli.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CategoriesApi
 */
@Ignore
public class CategoriesApiTest {

    private final CategoriesApi api = new CategoriesApi();

    
    /**
     * Return by category.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void categoriesCategoryIdGetTest() throws ApiException {
        String categoryId = null;
        Object response = api.categoriesCategoryIdGet(categoryId);

        // TODO: test validations
    }
    
    /**
     * Return a categories by site.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sitesSiteIdCategoriesGetTest() throws ApiException {
        String siteId = null;
        Object response = api.sitesSiteIdCategoriesGet(siteId);

        // TODO: test validations
    }
    
    /**
     * Predictor
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sitesSiteIdDomainDiscoverySearchGetTest() throws ApiException {
        String siteId = null;
        String q = null;
        String limit = null;
        Object response = api.sitesSiteIdDomainDiscoverySearchGet(siteId, q, limit);

        // TODO: test validations
    }
    
}
