/*
 * MELI Markeplace SDK
 * This is a the codebase to generate a SDK for Open Platform Marketplace
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package meli_marketplace_lib;

import meli.ApiException;
import meli.model.Item;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ItemsApi
 */
@Ignore
public class ItemsApiTest {

    private final ItemsApi api = new ItemsApi();

    
    /**
     * Return a Item.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void itemsIdGetTest() throws ApiException {
        String id = null;
        Object response = api.itemsIdGet(id);

        // TODO: test validations
    }
    
    /**
     * Update a Item.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void itemsIdPutTest() throws ApiException {
        String id = null;
        String accessToken = null;
        Item item = null;
        Object response = api.itemsIdPut(id, accessToken, item);

        // TODO: test validations
    }
    
    /**
     * Create a Item.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void itemsPostTest() throws ApiException {
        String accessToken = null;
        Item item = null;
        Object response = api.itemsPost(accessToken, item);

        // TODO: test validations
    }
    
}
