/*
 * MELI Markeplace SDK
 * This is a the codebase to generate a SDK for Open Platform Marketplace
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package meli_marketplace_lib;

import meli.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ItemsHealthApi
 */
@Ignore
public class ItemsHealthApiTest {

    private final ItemsHealthApi api = new ItemsHealthApi();

    
    /**
     * Return item health actions by id.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void itemsIdHealthActionsGetTest() throws ApiException {
        String id = null;
        String accessToken = null;
        Object response = api.itemsIdHealthActionsGet(id, accessToken);

        // TODO: test validations
    }
    
    /**
     * Return health by id.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void itemsIdHealthGetTest() throws ApiException {
        String id = null;
        String accessToken = null;
        Object response = api.itemsIdHealthGet(id, accessToken);

        // TODO: test validations
    }
    
    /**
     * Return health levels.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sitesSiteIdHealthLevelsGetTest() throws ApiException {
        String siteId = null;
        Object response = api.sitesSiteIdHealthLevelsGet(siteId);

        // TODO: test validations
    }
    
}
